### ISSUE TITLE
播放进度条控制器

### ISSUE THREAD

**Issue by azhon** [mengzhidaren/Vlc-sdk-lib#10]
播放进度条控制器怎么样才能刚好在视频的下面，而不是在容器的最底部。求解答！
<img src="http://i.imgur.com/934Yepb.png">

**Comment by mengzhidaren** [comment]
最外层设置一个固定高度就行了，你可以参考https://github.com/mengzhidaren/VlcPlayer

**Comment by azhong1011** [comment]
还发现一个问题，当正在播放视频的时候。退到桌面后然后在回去视频播放页面，视频怎么都播放不出。一定要重新初始化过才可以这个问题要怎么解决?

**Comment by mengzhidaren** [comment]
处里好activity的生命周期和surface的生命周期，
surface被回收时要释放掉
  mediaPlayer.getVLCVout().detachViews();  
回到前台在attached到surface上 
  mediaPlayer.getVLCVout().setVideoSurface(surface);
            mediaPlayer.getVLCVout().attachViews();

**Comment by azhong1011** [comment]
<img src="http://i.imgur.com/Q3vpSLX.png">我项目里使用了百度地图，然后在依赖你这个库。百度地图初始化就报错了。有解决方法吗？.我遇到的问题真tm多。。。。

**Comment by mengzhidaren** [comment]
自已解吧 只能帮你到这了

**Comment by azhong1011** [comment]
嗯，谢谢了

**Comment by azhong1011** [comment]
这几个方法是在自己写的类中调用，还是要在库中写。不知道写在哪里
mediaPlayer.getVLCVout().detachViews();
//播放视频的时候没有哪里有mediaPlayer的实例
mediaPlayer.getVLCVout().setVideoSurface(surface);
mediaPlayer.getVLCVout().attachViews();

**Comment by mengzhidaren** [comment]
这是自定义播放器用的  你就用我写好的videoview就行了 
 <org.videolan.vlc.VlcVideoView
        android:layout_width="match_parent"
        android:layout_height="match_parent" />

**Comment by Lddindasddf** [comment]
您好作者。我也遇到相同的问题。就是按了home键回到主页。按照您的方法。但是会花屏，不知道这个怎么解决
