### ISSUE TITLE
播放某个链接闪退。。。

### ISSUE THREAD

**Issue by GirlFriendNotFind** [mengzhidaren/Vlc-sdk-lib#102]
![1](https://user-images.githubusercontent.com/33824120/38968971-81cbf8f8-43c0-11e8-9c28-84598e5d05dd.png)
![2](https://user-images.githubusercontent.com/33824120/38968972-835ab61e-43c0-11e8-95ea-53648c2f6416.png)
播放
http://xxx.xx.xx.xx:8080/?resolution=0&type=0&gbid=34020000001320000001
发送闪退，不知道是流的原因还是播放器的原因呢？目前播放其它链接没有事。。

**Comment by GirlFriendNotFind** [comment]
问题是不是必现。。。但播放这个链接90%会闪退，其它链接的就没遇过

**Comment by GirlFriendNotFind** [comment]
又测试多百来次发现奔溃概率下降了40%左右，看不懂了，3.0.5版本。

**Comment by GirlFriendNotFind** [comment]
还有发现链接
connection failed: Connection refused
Your input can't be opened
不能打开的时候会卡死造成程序无响应

**Comment by mengzhidaren** [comment]
收到了，下个版本改吧 ，这版本问题还是有不少的
