### ISSUE TITLE
在播放界面上加一个 list， 点击显示list，或者刷新list数据时，播放画面会卡顿一下

### ISSUE THREAD

**Issue by Oliven09** [mengzhidaren/Vlc-sdk-lib#104]
在播放界面上加一个 list， 点击显示list，或者刷新list数据时，播放画面会卡顿一下，类似hdplive 播放界面，调出oklist，画面会卡一下。

**Comment by mengzhidaren** [comment]
啥意思没看懂

**Comment by Oliven09** [comment]
在播放页面加一个，显示多个界面播放清单的list，用来切换播放节目，类似HDP直播app，现在是显示这个list，画面就就会卡顿一下。

**Comment by mengzhidaren** [comment]
还是没看懂  ，你是说 播放器 切换media  释放时 或者 播放时  阻塞主线程了吗 ，你查看下具体是那个方法造成阻塞  产生卡顿的。或者你UI没适配好
