### ISSUE TITLE
播放4k视频卡顿的问题有没办法解决

### ISSUE THREAD

**Issue by gymiicmc** [mengzhidaren/Vlc-sdk-lib#106]
播放手机拍摄的一些视频会很卡（而此时手机自带播放器或者官方VLC的客户端不会卡）

**Comment by mengzhidaren** [comment]
我默认软解码的  你切换到硬件加速就行了

**Comment by gymiicmc** [comment]
找到了，在上层loadMedia中有setHWDecoderEnabled可以设置
