### ISSUE TITLE
播放以後使用 AudioRecord

### ISSUE THREAD

**Issue by rraayy** [mengzhidaren/Vlc-sdk-lib#109]
不知道您有沒有試過播放中以後使用AudioRecord來錄製聲音呢？
我發現startPlay 以後雖然 AudioRecord可以錄音，
但是vlc正在播放的畫面就沒有聲音了
關於這個部分不知道是否可以提攜指點一下該怎麼實作比較好呢

**Comment by mengzhidaren** [comment]
我刚更新的录制代码   播放中是有声音的     你确定有bug ?  提供下 版本 和 视频格式我试下
