### ISSUE TITLE
VLCVideoView设置有BUG

### ISSUE THREAD

**Issue by FSY-Specter** [mengzhidaren/Vlc-sdk-lib#11]
<org.videolan.vlc.VlcVideoView
            android:id="@+id/vlcVideoView"
            android:layout_width="match_parent"
            android:layout_height="wrap_content"/>
 android:layout_height变成了我整个屏幕的到不是图像的高

**Comment by mengzhidaren** [comment]
VlcVideoView就是一个textureview不能自动控制高度的，
textureview的surface实现方法是#248行  setTransform(txform);
你可以重写这个view在onMeasure里根据videosize的回调重置高度

**Comment by FSY-Specter** [comment]
你好！终于把源码下载下来了，看了你的源码，我直接很暴力的，在VlcVideoView.java中的adjustAspectRatio()里把偏移给干掉，加入        
ViewGroup.LayoutParams lp;
        lp=this.getLayoutParams();
        lp.height=newHeight;
        lp.width=newWidth;
        this.setLayoutParams(lp);
