### ISSUE TITLE
怎么让播放不停的缓冲不卡死

### ISSUE THREAD

**Issue by douya40** [mengzhidaren/Vlc-sdk-lib#115]
怎么让播放不停的缓冲不卡死

**Comment by mengzhidaren** [comment]
你这什么需求？ 缓冲最大cache也就60秒还和流的大小有关    在大点 如果是直播流和写一个保存直播流差不多了  点播的话就边下边播吧

**Comment by douya40** [comment]
我们需求就是rtsp连接如果断了就要不停的缓冲，没有时间限制，一直到用户退出

**Comment by mengzhidaren** [comment]
是断线重连的功能吗   我没写适配直播的播放器  你自已适配下吧

**Comment by douya40** [comment]
怎么搞
