### ISSUE TITLE
手机黑屏，再次点亮视频画面就不显示了

### ISSUE THREAD

**Issue by douya40** [mengzhidaren/Vlc-sdk-lib#117]
手机黑屏，再次点亮视频画面就不显示了

**Comment by mengzhidaren** [comment]
什么手机    你修改了什么配置没

**Comment by douya40** [comment]
华为，没有修改配置

**Comment by mengzhidaren** [comment]
你可以切换到硬解码试下  不行就把输出命令行改成android_display 
 比如  options.add("--vout=android_display,none");
