### ISSUE TITLE
不能播放RTSP流

### ISSUE THREAD

**Issue by OneDayNoMore** [mengzhidaren/Vlc-sdk-lib#118]
如题Log提示E/VLC: [cf032ab0/54ec] libvlc decoder: Timestamp conversion failed (delay 1713005, buffering 0, bound 9000000)
E/VLC: [cf032ab0/54ec] libvlc decoder: Could not convert timestamp 551395985643 for FFmpeg
这个应该怎么解决，用到得是: compile 'com.yyl.vlc:vlc-android-sdk:3.0.10'

**Comment by mengzhidaren** [comment]
请用官方的 vlc android播放器 测试没问题后，适配android配置参数参考官方issues
