### ISSUE TITLE
播放rtsp 非常卡，请问有什么办法解决

### ISSUE THREAD

**Issue by silence-jianghuan** [mengzhidaren/Vlc-sdk-lib#119]
rtsp://175.6.65.110:5638/pss/l_3601

**Comment by mengzhidaren** [comment]
卡的原因很多种情况，代码，网络，设备，服务器，  确定下原因在才能有解决方案

**Comment by silence-jianghuan** [comment]
你好 问题是在播放以后 卡在第一帧了，在pc端 播放是正常的。使用vlc官网的app播放也是一样的问题

**Comment by mengzhidaren** [comment]
如果官方APP也有问题就给官方提issues吧
