### ISSUE TITLE
同一个视频,在本地可以播放,放在服务器上不能播放,显示"Stop 播放已停止 有错误"

### ISSUE THREAD

**Issue by cdcdec** [mengzhidaren/Vlc-sdk-lib#12]
![010](https://cloud.githubusercontent.com/assets/8176067/20589173/c7eabe30-b255-11e6-9d47-315e7d8b7dcf.png)
同一个视频,在本地可以播放,放在服务器上不能播放,显示"Stop 播放已停止 有错误"，在log里面显示:VLC-std: [mov,mp4,m4a,3gp,3g2,mj2 @ 0xb7806680] moov atom not found

**Comment by mengzhidaren** [comment]
如果是直播流我不推荐用我这个播放器虽然也能用，但没其它专门做直播的播放器好(秒开)。要是普通的网络视频的话先用chrome测试一下，在找其它问题
