### ISSUE TITLE
视频播放一会儿，画面卡住，声音正常

### ISSUE THREAD

**Issue by milesniu** [mengzhidaren/Vlc-sdk-lib#123]
播放一会儿，或者seek多次会卡主画面，声音正常播放
控制台打印如下信息：
libvlc decoder: more than 5 seconds of late video -> dropping frame (computer too slow ?)
这个怎么解决？

**Comment by mengzhidaren** [comment]
你试下把 配置参数调整一下 
options.add("--avcodec-skiploopfilter");
options.add("4" );//4不去块 (最快)         0完全去块 (最慢)
options.add("--android-display-chroma");
  options.add(“RV32”);

**Comment by milesniu** [comment]
我加在init函数里面，是这样加吗？感觉没有什么效果，播放还是很卡，还有别的参数可设置吗？ 

 private void init() {

        ArrayList<String> options = VLCOptions.getLibOptions(getApplicationContext());
        options.add("--avcodec-skiploopfilter");
        options.add("4");//4不去块 (最快) 0完全去块 (最慢)
        options.add("--android-display-chroma");
        options.add("RV32");
        options.add("--vout=android_display,none");
        //加载库文件
        if (VLCInstance.testCompatibleCPU(this)) {
            Log.i("miles", "support   cpu");
        } else {
            Log.i("miles", "not support  cpu");
        }
    }

**Comment by mengzhidaren** [comment]
还有很多  调了也不明显 参考官网吧

**Comment by Roger1103** [comment]
> 还有很多调了也不明显参考官网吧

官网哪有
