### ISSUE TITLE
播放rtsp发现的一些问题

### ISSUE THREAD

**Issue by bifan-wei** [mengzhidaren/Vlc-sdk-lib#124]
您好，我尝试重复切换播放rtsp，发现以下一些问题，请教一下您：
1.加载切换播放过程中，有时候发现缓冲buffing从0直接到100了，到100后画面卡在上一个播放地址的最后一个画面。
2.有时候缓冲buffing到了100，但是画面还是显示黑屏，过一段时间可能十几秒或者一两分钟，才显示出画面。
对于上面的问题，应该怎么优化比较好么。

**Comment by mengzhidaren** [comment]
你试下把 配置参数调整一下
options.add("--avcodec-skiploopfilter");
options.add("4" );//4不去块 (最快) 0完全去块 (最慢)
options.add("--android-display-chroma");
options.add(“RV32”);
