### ISSUE TITLE
2.5.15

### ISSUE THREAD

**Issue by OneDayNoMore** [mengzhidaren/Vlc-sdk-lib#127]
2.5.15版本 会闪退
g E/vndksupport: Could not load vendor/lib/egl/libGLES_mali_v2.so from sphal namespace: dlopen failed: library "vendor/lib/egl/libGLES_mali_v2.so" not found.
06-27 17:58:10.862 22995-23064/com.ffcs.globaleyeplus.debug E/GTIntentService: onReceiveClientId -> clientid = 261b252c0eb48d459abc49b441e50ca8

**Comment by mengzhidaren** [comment]
升级到新版吧
