### ISSUE TITLE
有时会报anr异常，就是播放视频时，在视频链接无效没法播放

### ISSUE THREAD

**Issue by huanyuan** [mengzhidaren/Vlc-sdk-lib#129]
![qq 20180627151752](https://user-images.githubusercontent.com/12406954/42076035-0ac832e4-7ba6-11e8-8b80-cab504f24d5f.png)

**Comment by mengzhidaren** [comment]
用最新版本    还有问题先抛异常处理吧

**Comment by OneDayNoMore** [comment]
我使用的是3.0.13版本的  也会出现这样的问题

**Comment by mengzhidaren** [comment]
看log是restartplay有错误   我写的不一定对  你要改改了  参考下官方播放器的代码
