### ISSUE TITLE
播放视频时怎么设置自适应全屏

### ISSUE THREAD

**Issue by wangyongj** [mengzhidaren/Vlc-sdk-lib#13]
使用VlcVideoView时，播放图像四周有留白，怎么设置自动填充全屏，谢谢

**Comment by mengzhidaren** [comment]
四周有留白是软解的bug你在android6.0以上的版本切到硬解 6.0以下用软解会暂时解决下，后期我在改
if (android.os.Build.VERSION.SDK_INT >= 23) {
                media.setHWDecoderEnabled(true, true);
            } else {
                media.setHWDecoderEnabled(false, false);
            }

**Comment by wangyongj** [comment]
好的，谢谢
