### ISSUE TITLE
关于进度条的问题

### ISSUE THREAD

**Issue by GUEThe** [mengzhidaren/Vlc-sdk-lib#132]
![image](https://user-images.githubusercontent.com/19553651/42992857-667cf970-8c3c-11e8-96e3-82bf2b5d2047.png)
我这样调用播放视频，该怎么把MediaPlayer.Event.Buffering绑定到我自定义的进度条SeekBar上面呢？安卓新手，恳请大佬赐教。

**Comment by GUEThe** [comment]
![image](https://user-images.githubusercontent.com/19553651/42994801-b8bc27d8-8c41-11e8-8dfe-ddc6179384b0.png)
这样监听不起作用

**Comment by mengzhidaren** [comment]
新手的问题自已解   我帮你解了还有下一个问题等着你呢   多看下源代码   看不懂就多看下博客  一点点学
