### ISSUE TITLE
能不能隐藏takeSnapshot时左上角的preview？

### ISSUE THREAD

**Issue by tzraeq** [mengzhidaren/Vlc-sdk-lib#135]
如题，试过各种参数，比如:no-snapshot-preview，:no-osd，都不好用。求解决。

**Comment by mengzhidaren** [comment]
var_Create(p_vout, "snapshot-preview", VLC_VAR_BOOL);
    var_SetBool(p_vout,"snapshot-preview",false);
加到yyl_record.c 文件的 168 行

**Comment by tzraeq** [comment]
请问这个参数是还没暴露到java这一层么？

**Comment by mengzhidaren** [comment]
暂时没有   你只能下载下来改源码编译

**Comment by tzraeq** [comment]
谢谢，已经成功编译了，可以关闭了，另外设置osd为false可以隐藏截图路径的提示。供其他人参考。

**Comment by mengzhidaren** [comment]
太大了  上传不上来  配置文件就有2个G  还有其它环境  更大    除非连带模拟器打包 更大  费时费力
现在也能看到关键代码， 能用就行了

**Comment by azureplus** [comment]
打 patch？

**Comment by tzraeq** [comment]
> 打 patch？

不用，你fork一下mengzhidaren的库，然后找到对应位置，添加参数就可以了。
