### ISSUE TITLE
这个demo播不了https的视频

### ISSUE THREAD

**Issue by LuXGang** [mengzhidaren/Vlc-sdk-lib#136]
08-21 17:30:05.564 3181-3241/com.yyl.vlc E/VLC: [f0cabff0/ca9] libvlc tls client: Certificate verification failure: The certificate is NOT trusted. The certificate issuer is unknown. 
08-21 17:30:05.565 3181-3241/com.yyl.vlc E/VLC: [f0cabff0/ca9] libvlc tls client: TLS session handshake error
08-21 17:30:05.566 3181-3241/com.yyl.vlc E/VLC: [d35ae4b0/ca9] libvlc stream: HTTP connection failure
08-21 17:30:05.581 3181-3241/com.yyl.vlc E/VLC: [d204e030/ca9] libvlc input: Your input can't be opened
08-21 17:30:05.581 3181-3241/com.yyl.vlc E/VLC: [d204e030/ca9] libvlc input: VLC is unable to open the MRL 'https://upload.xianghunet.com/resources/videos/330109/201808/0a5ece0772c5dd50439ea7af7161f48091d67fd5.mp4'. Check the log for details.

**Comment by LuXGang** [comment]
https://upload.xianghunet.com/resources/videos/330109/201808/0a5ece0772c5dd50439ea7af7161f48091d67fd5.mp4

如何重新编译支持https的播放器呢？

**Comment by mengzhidaren** [comment]
可以播
