### ISSUE TITLE
用的哪个版本的vlc编译的？vlc官网上的最新版本是3.0.4

### ISSUE THREAD

**Issue by lingchen52** [mengzhidaren/Vlc-sdk-lib#140]
![image](https://user-images.githubusercontent.com/19205388/46711429-de296300-cc7e-11e8-93ff-a0414b78ebb0.png)

**Comment by mengzhidaren** [comment]
大神  点一下 下面android的图标  就是下面那个小机器人 就是那个版本 明白否？

**Comment by lingchen52** [comment]
看到了，我想自己编译vlc-android,环境是ubuntu18.04.1,NDK14,JDK1.8,SDK28,我按照官网的说明安装了所有依赖，配置好了环境变量，参照csdn上面的一些博客，始终编译失败，望指点

**Comment by mengzhidaren** [comment]
编译问题多google吧  每个人遇到的问题都不一样   要自已解决

**Comment by lingchen52** [comment]
你编译3.0.13版本的vlc用的什么环境？可以贴出来吗

**Comment by mengzhidaren** [comment]
我最后一次编译的环境重装电脑已经弄坏了   最近会重新在搭建一个，到时会贴出来 3.2.0版本的环境的

**Comment by azureplus** [comment]
> 看到了，我想自己编译vlc-android,环境是ubuntu18.04.1,NDK14,JDK1.8,SDK28,我按照官网的说明安装了所有依赖，配置好了环境变量，参照csdn上面的一些博客，始终编译失败，望指点

用 Ubuntu 16.04.5可以编译，18应该还不支持

**Comment by searchdingding** [comment]
demo在as3.2.1版本无法正常运行怎么回事
