### ISSUE TITLE
异常处理  

### ISSUE THREAD

**Issue by alanjuster** [mengzhidaren/Vlc-sdk-lib#142]
你好，有这样一种情况不知该怎么处理：
   在正常播放一段时间后，rtsp 播放源出现问题，这时客户端界面会卡在最后显示的那一帧  ，  没任何异常提示。
   这种该怎么处理？

**Comment by mengzhidaren** [comment]
应该会有提示的  打开日志 -vvv   多看下  media.setEventListener 和 mMediaPlayer.setEventListener   我记的是有回调的 忘记了  你试下
