### ISSUE TITLE
直播rtsp时，播放view左右两端黑边问题

### ISSUE THREAD

**Issue by mingxin-yang** [mengzhidaren/Vlc-sdk-lib#143]
播放界面两边会有黑边，显示的视频并不是被调整了宽高比，而是被裁切了（我对比了rtsp流和http流的视频，使用的是同一种初始化方法），使用adjustAspectRatio只能改变整体的宽高，并不能改变黑边的存在，请大神指教！
播放器的初始化如下
```
ArrayList<String> libOptions = VLCOptions.getLibOptions(this);
LibVLC libVLC = new LibVLC(this, libOptions);
media = new Media(libVLC, Uri.parse(mUrl));
media.setHWDecoderEnabled(false, false);
media.addOption(":network-caching=100");
mediaPlayer = new MediaPlayer(media);
mSurfaceView.setMedia(mediaPlayer);
mSurfaceView.startPlay();
```
我试了三个链接
> http://192.72.1.1/SD/Normal/FILE181022-142119-001383.MOV
> file:///storage/emulated/0/autobot/camera/movie/FILE181012-162019-000009.MOV
> rtsp://192.72.1.1/liveRTSP/v1
前两个链接显示是没有问题的，唯独第三个被剪裁了

**Comment by mengzhidaren** [comment]
用电脑端的vlc测试下   如果没问题   在尝试切换OpenGL的开关 在VLCOptions.java  74行

**Comment by mingxin-yang** [comment]
电脑端的也是截断的，有什么方法可以将视频拉伸呢

**Comment by mengzhidaren** [comment]
检查下推流的配置吧，最好在电脑端适配好

**Comment by mingxin-yang** [comment]
解决了，设置了一下mediaplayer的宽高比   
mediaPlayer.setAspectRatio("16:9");
