### ISSUE TITLE
视频没法拉伸铺满View

### ISSUE THREAD

**Issue by HelloTodayWolrd** [mengzhidaren/Vlc-sdk-lib#145]
需求是要不管视频的原尺寸比例，总是要拉伸画面铺满播放View。我调用了mMediaPlayer.setAspectRatio(width + ":" + height); mMediaPlayer.setScale(0); 视频还是没能拉伸铺满的（width和height都是View的大小）。要怎么做呢，可否指教一二。

**Comment by mengzhidaren** [comment]
setScale是在打开VLCOptions.isSupportsOpenGL下才有效  参考demo   不支持openGL时用VlcVideoView.adjustAspectRatio

**Comment by wangmubiao** [comment]
谢谢大佬回复。
public void onNewVideoLayout(IVLCVout vlcVout, int width, int height, int visibleWidth, int visibleHeight, int sarNum, int sarDen)
	{
		if (width * height == 0) return;
		adjustAspectRatio(visibleWidth,  visibleHeight);
	}
这个回调函数里width, height, visibleWidth, visibleHeight, sarNum这几参数的值都是0，没能调用adjustAspectRatio。之前用的2.1.2版本的vlc的setAspectRatio和setScale都是有效。

**Comment by wangmubiao** [comment]
@mengzhidaren 有个严重的问题，不知道您是否遇到过：Fatal signal 11 (SIGSEGV), code 1, fault addr 0xdead1234 in tid 6005 (JNISurfaceTextu)，这个闪退错误。我这里反复播放一个本地的小视频，一段时间（大概半个小时，就会出现这个闪退错误。切换了其他版本的vlc（v3.0.13，v3.0.0，v2.1.2）还是有这个问题。困惑，百思不得其解。

**Comment by mengzhidaren** [comment]
可以去官方仓库提交bug
