### ISSUE TITLE
Previous video image cache show on second video start 

### ISSUE THREAD

**Issue by MinChanSike** [mengzhidaren/Vlc-sdk-lib#146]
When I try to **play/stop** two rtsp stream, first video image is show a while before second video frames are received. How to clean first video frame on stop?

**Comment by mengzhidaren** [comment]
Try closing video is  MediaPlayer.setVideoTrackEnabled(false)

**Comment by MinChanSike** [comment]
Although I try to set VideoTrackEnabled: **false**, still not working.

`player.onStop();`
`player.getMediaPlayer().setVideoTrackEnabled(false);`

First video's last frame is still showing when second video is buffering.

**Comment by mengzhidaren** [comment]
SetVideoTrack Enabled (false) doesn't seem to work , so try hiding the front with a picture or drawing a solid background  use  onSurfaceTextureUpdated(SurfaceTexture surface)
