### ISSUE TITLE
libvlc的截图和录像这么不稳定，请问大神有跨平台的解决方案么？

### ISSUE THREAD

**Issue by tzraeq** [mengzhidaren/Vlc-sdk-lib#147]
如题，libvlc的截图和录像这么不稳定，请问大神有跨平台的解决方案么？我要同时做android和ios。

**Comment by mengzhidaren** [comment]
有收费的公司可以定制这个功能，目前开源的播放器里很少有支持的，也可以修改vlc源码编译两个平台共用，如果你技术高一点可以用FFMPEG重新写个播放器在 av_read_frame(avFormatContext, avPacket)这里实现你自定义的方法录像截图都行

**Comment by tzraeq** [comment]
你好，截图不稳定的问题，我看了一下日志，大概找到了问题，在X86的模拟器上，会打印“libvlc filter: looking for video converter module matching "any": 20 candidates”，在arm的真机上，会打印“libvlc filter: looking for video converter module matching "any": 16 candidates”，少了这4个，所以导致截图失败。不知道你的编译脚本里对不同的cpu平台参数有什么特殊处理？截图成功的情况下，还会打印“libvlc filter: using video converter module "swscale"”，而截图失败的情况下会对每一个converter进行一次尝试，最后宣告失败。

**Comment by tzraeq** [comment]
另外还有一个细节，x86的模拟器是android5.1，真机是android7.0+

**Comment by mengzhidaren** [comment]
这样看起来，你这状况只能自已搭环境去编译自定义库解决问题了，但我感觉不会这么麻烦，官方的库基本解决9成问题了，你多调试下找到问题在解决吧

**Comment by tzraeq** [comment]
谢谢。那我再试试。

**Comment by carmanlwf** [comment]
推荐使用qtav
