### ISSUE TITLE
播放rtsp延时很高，怎么配置？

### ISSUE THREAD

**Issue by leestars** [mengzhidaren/Vlc-sdk-lib#149]

**Comment by mengzhidaren** [comment]
去官方文档里找配置参数  每个人的配置都不一统一

**Comment by leestars** [comment]
可以给一下链接吗？我找不到

**Comment by mengzhidaren** [comment]
https://wiki.videolan.org/VLC_command-line_help
最好下载源代码 ， 在源码里找配置参数 
https://github.com/videolan

**Comment by leestars** [comment]
我只使用了armeabi-v7a的so，在高通845处理的手机上，不能正常的播放，播放一直是这样的？![image](https://github.com/leestars/images/blob/master/vlc_error.png)

**Comment by mengzhidaren** [comment]
发log  不要发图片
