### ISSUE TITLE
can't play stream with character '*' in url 

### ISSUE THREAD

**Issue by boxstore** [mengzhidaren/Vlc-sdk-lib#156]
can't play stream with character '*' in url

**Comment by mengzhidaren** [comment]
Why did the server give you the address of ‘* and let the server change it?

**Comment by boxstore** [comment]
link stream from google. 
xxx/*/xxx
can you fix it ?
thanks

**Comment by mengzhidaren** [comment]
Attempt to escape the special characters in the URL of the Web site,  * is  %2A ,  like:  xxx/%2A/xxx
