### ISSUE TITLE
安卓工控机上播放rtsp视频流

### ISSUE THREAD

**Issue by vip404** [mengzhidaren/Vlc-sdk-lib#159]
我在模拟器上调试是可以的，但是放到真实机器上会报error pinging server
/HttpProxyCacheServer: Proxy cache server started. Is it alive? false
![image](https://user-images.githubusercontent.com/43853364/58521882-aa408500-81f0-11e9-9615-fe879e33dbc6.png)
E/dalvikvm: Could not find class 'org.videolan.libvlc.MediaPlayer$3', referenced from method org.videolan.libvlc.MediaPlayer.createAudioDeviceCallback

这是为什么啊，真实机器是安卓4.4

**Comment by mengzhidaren** [comment]
把demo里的lib本地引用注释掉，
 先用jconter里的库  compile 'com.yyl.vlc:vlc-android-sdk:3.0.13'

**Comment by vip404** [comment]
解决了，谢谢大佬
