### ISSUE TITLE
怎么减小或者取消buffer呢?buffer加载有点久

### ISSUE THREAD

**Issue by gh6220755** [mengzhidaren/Vlc-sdk-lib#16]

**Comment by mengzhidaren** [comment]
这个问题真好，我也要解决，但是现实是束手无策，因为c的源码太多我还没搞懂呢

**Comment by gh6220755** [comment]
@mengzhidaren 有没有看过这篇文章呢?http://blog.csdn.net/qiaoliang328/article/details/21176331,可能会提供一些思路,在java层修改network-caching的值,没什么效果.运行的时候看到打印了ANW:setbufferCount 一串16进制码 5,然后我本地验证,这后面的5恰好就是缓存时间5秒,所以我估计就和这个打印的有关系

**Comment by mengzhidaren** [comment]
谢谢你找问题，因为我在公司太忙了，所以这些问题要解决说快也快，只是时间的问题，最近在忙别的，我也在收集这种问题和其它bug，有时间一次性改源码上传，你要比较急就自已改源码编译一下。现在要优化的地方太多了，没时间

**Comment by gh6220755** [comment]
@mengzhidaren 那你有源码没?我git chone半天都get不下来

**Comment by gh6220755** [comment]
@mengzhidaren  我直接是根据vlc官网上面的地址git的,但是一直git不下来

**Comment by mengzhidaren** [comment]
我源码有点多10G 你开代理下吧

**Comment by gh6220755** [comment]
@mengzhidaren 我用最新的源码编译出来,光一种cpu架构就有将近80M,libvlc.so这个文件就有70多M,是不是我编译方式出错了哦?

**Comment by mengzhidaren** [comment]
把vlc-android 编出来装手机上能播放视频就行了  .so正常是不超20M的  你编的有点问题
