### ISSUE TITLE
3.0.13问题

### ISSUE THREAD

**Issue by wangbinjc** [mengzhidaren/Vlc-sdk-lib#161]
#21605 SIGSEGV(SEGV_MAPERR)

#01 pc 002c35a5 /data/app-lib/com.yjy.musicplayer-1/libvlcjni.so [armeabi-v7a]

**Comment by wangbinjc** [comment]
偶现这种so库错误，不知道什么情况，更新3.0.13版本之前没有出现过这种错误，大神能不能帮忙看下？

**Comment by mengzhidaren** [comment]
向官方仓库提这种 bug 吧
