### ISSUE TITLE
建议添加更多的VLC接口

### ISSUE THREAD

**Issue by dahai2626** [mengzhidaren/Vlc-sdk-lib#162]
非常感谢能提供VLC SDK的模块。但目前使用来说部分VLC原有的功能并未在Java层公开，比如setVideoFormat，setVideoCallback （获取每一帧数据）等接口，希望作者能更新更多的接口，方便大家更好的调用。
再次感谢你为大家作出的贡献！

**Comment by mengzhidaren** [comment]
我现在公司早就不用这个了，加新功能费时费力，不一定有时间，还是跟着官方版本走吧
