### ISSUE TITLE
我测试其他人的 vlc android  sdk，播放rtmp 延时6秒以上，你这个延时能控制在1~3秒吗

### ISSUE THREAD

**Issue by 1395881288** [mengzhidaren/Vlc-sdk-lib#163]
我测试其他人的 vlc android  sdk，播放rtmp 延时6秒以上，你这个延时能控制在1~3秒吗

**Comment by 1395881288** [comment]
刚刚支付宝你了，哈哈。

**Comment by mengzhidaren** [comment]
要专门优化直播的话就要裁剪不用的一堆库比如文件协议，编解码库等等，还要改里面很多代码重新打包编译，定制成自已用的库。想节省时间的话，还是建议你用B站的ijk，代码问题会有人及时回复，改VLC的源码一有错误几乎没啥资料，不是大牛的话就别在vlc上费时间了，这个库只是很小众的播放器

**Comment by 1395881288** [comment]
好 谢谢。

**Comment by mojizx** [comment]
> 我测试其他人的 vlc android sdk，播放rtmp 延时6秒以上，你这个延时能控制在1~3秒吗

你好 我能请教你下嘛 　QQ　４４６７１７１１２　我弄这个好久啦　但是还是没有弄出来　哎
