### ISSUE TITLE
同时播放多路视频时，当网络不好时，视频还在加载中，关闭播放，会出现anr

### ISSUE THREAD

**Issue by infelt** [mengzhidaren/Vlc-sdk-lib#164]
![image](https://user-images.githubusercontent.com/7675827/60868301-4ed9cc00-a25f-11e9-8103-06122b8f6b71.png)

好像是处理这个nativeSetVideoTrack时间过长。
感谢作者想，希望可以给出解决建议！

**Comment by mengzhidaren** [comment]
去官方仓库提issues吧

**Comment by wjj201411** [comment]
> ![image](https://user-images.githubusercontent.com/7675827/60868301-4ed9cc00-a25f-11e9-8103-06122b8f6b71.png)
> 
> 好像是处理这个nativeSetVideoTrack时间过长。
> 感谢作者想，希望可以给出解决建议！
有解决办法了吗？我也遇到这个问题，不知怎么处理，时不时卡死
