### ISSUE TITLE
Play multicast stream HD content mp4/h264 not high fps.

### ISSUE THREAD

**Issue by anhlevfx** [mengzhidaren/Vlc-sdk-lib#166]
Hello,

I try your demo sample with our multicast tream. SD content play very smooth, but HD content play not high fps, format HD content is mp4/h264.

What should I need to do get higher fps? Now it's very not good experience.

**Comment by mengzhidaren** [comment]
In the official Android player test, if supported, in the modification of parameter configuration

**Comment by anhlevfx** [comment]
I try VLC on GoogleTV store, and it play smooth HD content same multicast url. I don't know what parameter should I config to speed up decode mp4/h264 content. Video is choppy when use your default setting.

**Comment by mengzhidaren** [comment]
Try switching hardware to accelerate media. setHWDecoderEnabled (bool);
Rewriting the getLibOptions (Context context) method
Control block parameters
Options. add ("--avcodec-skiploopfilter");
Options. add ("""+getDeblocking (-1));
and
Options. add ("- android-display-chroma");
Options. add ('YV12');

**Comment by anhlevfx** [comment]
I try
LibVLC libVLC = VLCInstance.get(getContext());
Media media = new Media(libVLC, Uri.parse("udp://xxx.x.x.x:xxxxxx")); // I need keep secret ip and port because of company rules.
media.setHWDecoderEnabled(true, true);
ArrayList<String> options = VLCOptions.getLibOptions(getContext());
options.set(2, "4"); //force --avcodec-skiploopfilter value is "4"
vlcVideoView.setMedia(new MediaPlayer(libVLC));
vlcVideoView.startPlay();

But it look not better. With SD content, box (AndroidTV) armv7 play very smooth

**Comment by mengzhidaren** [comment]
ArrayList options = VLCOptions.getLibOptions(getContext());//rewrite
//......
LibVLC libVLC = new LibVLC(context,options);  //try

**Comment by anhlevfx** [comment]
Thank you for your support, quality better but not smooth enough. Did you try play multicast mp4/h264 FullHD before?

**Comment by mengzhidaren** [comment]
没有过，你去官方仓库看看吧
