### ISSUE TITLE
libvlc_media_new_callbacks 如何使用read回调

### ISSUE THREAD

**Issue by zjx94** [mengzhidaren/Vlc-sdk-lib#168]
你好，我在用libvlc_media_new_callbacks这个函数时出现了疑问。其中的回调我就简略说成open\read。我使用的场景是读一个网络流。我做法是在open中打开流，在read中读流数据并给到buf。
疑问是：
1、open中的datap是传递给read作为read的第一个参数opaque吗？sizep是作为read中buf的大小吗？（我实践觉得datap就是传递为read的opaque,而sizep似乎不是read中buf的大小）
2、read中的buf大小是多少，这个buf是每读一次就会减小还是每次都是固定大小，还是可以自己改动？（我的情景是需要buf最好能改变大小，因为流数据大小不一样）
3、除了这个libvlc_media_new_callbacks，还有没有办法能拿到解码前的数据，因为需要进行一些数据分析。
谢谢。

**Comment by mengzhidaren** [comment]
我快两年多没看源码了，源码更新也快，我也没空，帮不了你，你还得自已解决，我一般是跟距 option的配置参数追踪源码找到方法 去解决问题的，希望对你有用吧
