### ISSUE TITLE
有在Mac上编译过么?

### ISSUE THREAD

**Issue by azureplus** [mengzhidaren/Vlc-sdk-lib#17]

**Comment by mengzhidaren** [comment]
没有    mac便宜的不想买 贵的买不起

**Comment by azureplus** [comment]
{standard input}: Assembler messages:
{standard input}:270: Error: unknown register alias 'TMP'
{standard input}:272: Error: unknown register alias 'LEN'
clang38: error: assembler command failed with exit code 1 (use -v to see invocation)
make[1]: *** [libavcodec/arm/fmtconvert_vfp.o] Error 1
{standard input}: Assembler messages:
{standard input}:365: Error: unknown register alias 'QA'
{standard input}:367: Error: unknown register alias 'QB'
{standard input}:422: Error: unknown register alias 'QA'
{standard input}:424: Error: unknown register alias 'QB'

**Comment by azureplus** [comment]
最近遇到这种问题了,你的这个库,新版本貌似不兼容,还请你发一个新版本吧,把你的版本放在vlc-android上,很多Api不存在了,谢谢了

**Comment by mengzhidaren** [comment]
你描述的问题不是很清楚     不过  现在vlc在github上最新的是2.2.0  我有时间就编一下在上传

**Comment by azureplus** [comment]
好 谢谢你了

**Comment by azureplus** [comment]
@mengzhidaren 
Android NDK:     This is likely to result in incorrect builds. Try using LOCAL_STATIC_LIBRARIES    
Android NDK:     or LOCAL_SHARED_LIBRARIES in

Ubuntu 16.04.1 出现的问题,还请指教一下

**Comment by mengzhidaren** [comment]
解不完的问题  多google吧  会学点东西
