### ISSUE TITLE
可以修改你的源代码么

### ISSUE THREAD

**Issue by qq12cvhj** [mengzhidaren/Vlc-sdk-lib#170]
可以修改你的代码么，包括你有一点改动的c和java的libvlc内容，根据自己需求更改一些内容。我是将libvlc和jni的库都编译好了，但是对于api 的使用，还是有些陌生，不过有了作者你的代码，的确对java版的api更熟悉了一步，包括结构这些。我在代码中声明来源，可以修改你的代码么

**Comment by mengzhidaren** [comment]
可以，随便改吧，发布到你个人的仓库，声明来源就行了
