### ISSUE TITLE
请问可以当做列表中的item使用么

### ISSUE THREAD

**Issue by GiveSmile** [mengzhidaren/Vlc-sdk-lib#171]

**Comment by mengzhidaren** [comment]
可以

**Comment by GiveSmile** [comment]
感谢 您的解答&nbsp; 方便问一下您&nbsp; 如何将进度条 那个取消掉么&nbsp; 因为如果 放在列表中的话 滑动时 进度条会出现一定程度的UI问题


------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"yuyunlong"<notifications@github.com&gt;;
发送时间:&nbsp;2019年11月12日(星期二) 下午3:19
收件人:&nbsp;"mengzhidaren/Vlc-sdk-lib"<Vlc-sdk-lib@noreply.github.com&gt;;
抄送:&nbsp;" "<1633791475@qq.com&gt;;"State change"<state_change@noreply.github.com&gt;;
主题:&nbsp;Re: [mengzhidaren/Vlc-sdk-lib] 请问可以当做列表中的item使用么 (#171)




可以
