### ISSUE TITLE
怎么支持IPV6

### ISSUE THREAD

**Issue by OneDayNoMore** [mengzhidaren/Vlc-sdk-lib#175]
如题 我想要播放IPV6 在官网上查找到参数设置

 --dscp=<integer>           DiffServ Code Point
          Differentiated Services Code Point for outgoing UDP streams (or IPv4
          Type Of Service, or IPv6 Traffic Class). This is used for network
          Quality of Service.

但是这个参数应该怎么设置呢

**Comment by mengzhidaren** [comment]
先传参数可试下 看下log     如果没有这个功能 需要 动态链接库里打开 编译下依赖库

**Comment by OneDayNoMore** [comment]
还是播不了  博主有空帮忙研究一下 谢谢
