### ISSUE TITLE
vlc 播放rtsp，断开网络程序会ANR,有修复这种问题吗

### ISSUE THREAD

**Issue by zijin2014** [mengzhidaren/Vlc-sdk-lib#176]

**Comment by mengzhidaren** [comment]
用官方 vlc 播放器测试下  如果还有问题可以提issues到官方仓库

**Comment by wjj201411** [comment]
> 用官方 vlc 播放器测试下 如果还有问题可以提issues到官方仓库
官方播放器播放页面结束掉了，但是没有无响应

**Comment by mengzhidaren** [comment]
好吧  我抽空同步一下最新的仓库版本吧   最近有点忙

**Comment by wjj201411** [comment]
好的，给力！

**Comment by zijin2014** [comment]
播放发烫严重呢，这是啥导致的呢

**Comment by mengzhidaren** [comment]
可以尝试修改 libvlc/src/main/java/com/vlc/lib/listener/util/VLCOptions.java#L119     别的地方对性能消耗影响不大
