### ISSUE TITLE
可以去掉什么文件

### ISSUE THREAD

**Issue by janzen** [mengzhidaren/Vlc-sdk-lib#18]
请问有什么是可以删除的吗
刚接触vlc  还没搞懂   
想用到自己的项目里 无奈包太大
libvlc 里的文件 可以删减的

**Comment by mengzhidaren** [comment]
ndk {
            //支持的abi   ,'x86_64','arm64-v8a','x86'等
            abiFilters 'armeabi-v7a'
        }
只保留你要支持的平台 armeabi-v7a

**Comment by azureplus** [comment]
@mengzhidaren 你在Ubuntu下编译出现过什么问题么?直接安卓官方的编译手册,就编译成功了么

**Comment by mengzhidaren** [comment]
会出现很多错误的  要google一个一个解
