### ISSUE TITLE
rtsp流 延迟问题

### ISSUE THREAD

**Issue by wcg2000** [mengzhidaren/Vlc-sdk-lib#184]
这个问题有人问过，
我试过windows 上的 VLC MEDIA PLAYER，可以设置成最低延迟，效果很好；
这个sdk怎么配置的？
已设如下
 media.addOption(":network-caching=100");

**Comment by wcg2000** [comment]
hello

**Comment by wcg2000** [comment]
https://blog.csdn.net/weixin_33943347/article/details/90309476
参考这个，得重新编译吗

**Comment by mengzhidaren** [comment]
也可以不用重新编译，直接在JNI层获取到播放器引用对像修改配置，参考我如何拍照截图的功能是一样的逻辑去修改，
