### ISSUE TITLE
VLC接局域网的RTSP流,时间比较久的时候会出现掉帧，卡屏，花屏，之后延迟变大，变成10s以上

### ISSUE THREAD

**Issue by ILoveLin** [mengzhidaren/Vlc-sdk-lib#186]
E/VLC: [0000007d484d8590/cc3] libvlc decoder: Timestamp conversion failed (delay 1727583, buffering 0, bound 3000000)
E/VLC: [0000007d484d8590/cc3] libvlc decoder: Could not convert timestamp 57225788676 for FFmpeg
E/VLC: [0000007d484d8590/cc3] libvlc decoder: Timestamp conversion failed (delay 1727583, buffering 0, bound 3000000)
E/VLC: [0000007d484d8590/cc3] libvlc decoder: Could not convert timestamp 57225810009 for FFmpeg
a NULL string not supported here.
E/VLC: [0000007d484d8590/cc3] libvlc decoder: Timestamp conversion failed (delay 1727583, buffering 0, bound 3000000)

这个是log日子 我百度了，说是时间戳的问题，但是我不会编译，所以有请博主，想办法解决下，长时间直播录屏的时候花屏，掉线， 录像3个小时问题比较多

**Comment by mengzhidaren** [comment]
去官方仓库里提交这个issues  有人会解决

**Comment by ILoveLin** [comment]
直接搜索VLC吗？

**Comment by mengzhidaren** [comment]
官方一直在维护，代码有问题直接跟开发者留言就行了，快的话下个版本就修复好了   https://code.videolan.org/videolan/vlc-android

**Comment by ILoveLin** [comment]
您好博主,首先谢谢你的开源项目哈
我现在换ijkplayer 了,添加了录像截图功能(rtsp rtmp http https 等等支持所有cpu架构),还在测试,时间久会不会丢帧问题，感觉不会出现卡顿 掉帧问题，
等我这边确定OK了，我可以发给Demo 博主看下，您可以添加到，您的github项目里面去，因为也有很多和我一样的开发者需求这样的功能。您那边start比较多我就不再写一个项目了哈哈


| |
tongzhengtong
|
|
tongzhengtong@126.com
|
签名由网易邮箱大师定制
在2021年1月5日 16:09，yuyunlong<notifications@github.com> 写道：

官方一直在维护，代码有问题直接跟开发者留言就行了，快的话下个版本就修复好了 https://code.videolan.org/videolan/vlc-android

**Comment by ILoveLin** [comment]
您好,咨询个问题  trsp直播的时候直播流断开连接的时候,是会走回调监听,但是RTMP直播的时候断开连接不走回调监听?不知道为啥?

**Comment by mengzhidaren** [comment]
我很久不看 VLC 了，在忙别的项目，帮不上忙了

**Comment by ILoveLin** [comment]
没事  谢谢哈
