### ISSUE TITLE
编译错误?

### ISSUE THREAD

**Issue by azureplus** [mengzhidaren/Vlc-sdk-lib#19]
Android NDK: WARNING:private_libs/Android.mk:iomx.13: non-system libraries in linker flags: -lgcc -lstagefright -lmedia -lutils -lbinder -lcutils -lui    
Android NDK:     This is likely to result in incorrect builds. Try using LOCAL_STATIC_LIBRARIES    
Android NDK:     or LOCAL_SHARED_LIBRARIES instead to list the library dependencies of the   

vlc/modules/video_output/android/nativewindowpriv.c:49:10: fatal error: 'ui/android_native_buffer.h' file not
      found
#include <ui/android_native_buffer.h>

**Comment by mengzhidaren** [comment]
这个我不能帮你看log了  ，看似有个文件ndk没找到，像这种错没法回答，你出错很正常 你还会有其它错误的  不一定是什么    自行google吧  不然和你聊不完的error

**Comment by azureplus** [comment]
这个原因 我找到了 当时没有把依赖库引入 
Mac下编译不了 原因找不到

发自我的 MyPhone
