### ISSUE TITLE
RTSP有声音没画面

### ISSUE THREAD

**Issue by lizhAndroid** [mengzhidaren/Vlc-sdk-lib#195]
电脑端vlc可以播放，但是手机上不能播放，运行这个项目也是只有声音没有画面，流的信息如下
![image](https://user-images.githubusercontent.com/47814979/178402881-9a2884bc-fa3a-41de-bc09-e0b5bc2ebfb1.png)

**Comment by mengzhidaren** [comment]
这个格式  要在编译vlc库文件的时候 开启 才能支持吧  你重新编译下解码器就行了

**Comment by lizhAndroid** [comment]
>

**Comment by lizhAndroid** [comment]
好像编码是没问题的，同样的编码有些是可以播放的，不同的是分辨率，2560的不能播放，1440的可以播放，请问有针对大分辨率的配置可以参考吗

**Comment by mengzhidaren** [comment]
在option 里有输出大小的配置   可以找找    如果不行就在解码时  只解码一半显示   有些配置低的手机cpu处理不了太高分辨率的视频
