### ISSUE TITLE
播放无法马上停止和安装包太大

### ISSUE THREAD

**Issue by FrankLove** [mengzhidaren/Vlc-sdk-lib#20]
感谢博主的编译，现在有两个问题想请教下
1、把你的sdk加入到项目中，安装包飙升到了70多MB，有什么办法可以在你这个sdk里面减少安装包体积吗？
2、播放rtmp流的时候，如果播放地址不对，在加载的过程中这个时候如果退出播放界面会卡住很久，查看log显示无法马上结束播放，如果正常播放视频，那么可以立刻结束。下面是日志
12-19 22:18:55.720 16310-16310/com.lancoo.coursecenter I/System.out: ----------------Opening 
12-19 22:18:55.720 16310-16310/com.lancoo.coursecenter I/System.out: ----------------Buffering 正在缓冲
12-19 22:18:55.720 16310-16310/com.lancoo.coursecenter I/System.out: -------------showProgressDialog message 正在缓冲...
12-19 22:18:55.720 16310-16310/com.lancoo.coursecenter I/System.out: ----------------Buffering 
12-19 22:19:02.920 16310-16310/com.lancoo.coursecenter D/*********VLCPlayerActivity*********: onBackPressed: 
12-19 22:19:02.930 16310-16310/com.lancoo.coursecenter D/*********VLCPlayerActivity*********: pausePlay: 
12-19 22:19:31.790 16310-18325/com.lancoo.coursecenter D/flag: true验证了
12-19 22:20:18.430 16310-27294/com.lancoo.coursecenter D/VLC: [61cc5760/6a9e] core stream: net: connecting to  port 554
12-19 22:20:18.430 16310-27294/com.lancoo.coursecenter E/VLC: [61cc5760/6a9e] access_realrtsp stream: cannot connect to :554
12-19 22:20:18.430 16310-27294/com.lancoo.coursecenter E/VLC: [61cc5760/6a9e] core stream: Connection failed
12-19 22:20:18.450 16310-27294/com.lancoo.coursecenter E/VLC: [61cc5760/6a9e] core stream: VLC could not connect to ":554".
12-19 22:20:18.450 16310-27294/com.lancoo.coursecenter D/VLC: [61cc5760/6a9e] access_realrtsp stream: could not connect to: 
12-19 22:20:18.460 16310-27294/com.lancoo.coursecenter E/VLC: [61cc5760/6a9e] nfs stream: nfs_parse_url_incomplete failed: 'Invalid URL specified'
12-19 22:20:18.470 16310-27294/com.lancoo.coursecenter D/VLC: [61cc5760/6a9e] core stream: no access modules matched
12-19 22:20:18.490 16310-27294/com.lancoo.coursecenter E/VLC: [61cc55f8/6a9e] core input source: cannot access ://
12-19 22:20:18.490 16310-27294/com.lancoo.coursecenter D/dalvikvm: threadid=30: thread exiting, not yet detached (count=0)
12-19 22:20:18.500 16310-16310/com.lancoo.coursecenter D/VLC: [62f99268/3fb6] core input: Destroying the input for '(null)'
12-19 22:20:18.500 16310-16310/com.lancoo.coursecenter D/VLC: [61a080d8/3fb6] core audio output: removing module "opensles_android"
12-19 22:20:18.520 16310-16310/com.lancoo.coursecenter I/****MyScanActivity****: ***mEndTime = 1482157218525, duration = 82***
12-19 22:20:18.530 16310-16310/com.lancoo.coursecenter I/System.out: ----------------onPause
12-19 22:20:18.540 16310-16310/com.lancoo.coursecenter I/System.out: ---------------onResume 
12-19 22:20:18.600 16310-16310/com.lancoo.coursecenter I/System.out: ---------isshowCheckbox  false   Constdefine.IS_ADMIN true
12-19 22:20:18.600 16310-16310/com.lancoo.coursecenter I/System.out: ---------isshowCheckbox  false   Constdefine.IS_ADMIN true
12-19 22:20:18.620 16310-16310/com.lancoo.coursecenter D/PullToRefresh: First Visible: 0. Visible Count: 5. Total Items:5
12-19 22:20:18.670 16310-16310/com.lancoo.coursecenter I/System.out: ----------------onStop
12-19 22:20:18.670 16310-16310/com.lancoo.coursecenter D/*********VLCPlayerActivity*********: onDestroy: 
从点击onBackPressed到打印vlc下面的日志大概需要15秒左右
返回操作执行的代码是这样的
        if (mediaPlayer.isPlaying()) {
            mediaPlayer.pause();
            imgPlay.setBackgroundResource(R.drawable.videoviewx_play);
        }

        mediaPlayer.stop();
        vlcVout.detachViews();

        seekBarTime.setOnSeekBarChangeListener(null);
//        seekBarVolume.setOnSeekBarChangeListener(null);
        vlcVout.removeCallback(callback);
        mediaPlayer.setEventListener(null);
 mediaPlayer.release();

**Comment by mengzhidaren** [comment]
第一个问题 可以配置支持的库去掉用不到的.so
ndk {
            //支持的abi   , //'x86_64'//, 'arm64-v8a'
            abiFilters 'armeabi-v7a'//,'x86_64','arm64-v8a','x86'
        }
第二个问题 我没遇到过 不过要解决要改源代码 我忙 没时间   
我有个想法你可以尝试下，不用release  全局只new一个mediaplayer 直接切换播放源media

**Comment by FrankLove** [comment]
@mengzhidaren 请问第一个问题的ndk 这个修改是在哪个呢，是要自己编译源码吗，还是可以在你的工程里修改
第二个问题，我用你的demo测试是没有这个问题的，我现在做的是用你的sdk里面的库，但是自己重新写了一个播放类。下面是我播放的代码，不知道有什么问题
`//初始化vlc播放
            ArrayList<String> options = new ArrayList<String>();
            //options.add("--subsdec-encoding <encoding>");
            options.add("--aout=opensles");
            options.add("--audio-time-stretch"); // time stretching
            options.add("-vvv"); // verbosity
            LibVLC libvlc = LibVLCUtil.getLibVLC(options,getApplicationContext());
            mediaPlayer = new MediaPlayer(libvlc);
            vlcVout = mediaPlayer.getVLCVout();

            vlcVout.addCallback(callback);
            vlcVout.setVideoView(surfaceView);
            vlcVout.attachViews();

             Media media = null ;

            if(mRes == null)
            {
                System.out.println("-----------mRes is null");
                mSideBar.setVisibility(View.GONE);
                WindowManager wm = this.getWindowManager();
                surfacewidht = wm.getDefaultDisplay().getWidth();
                surfaceHeight = (int)(surfacewidht*(0.75));
                ViewGroup.LayoutParams lp = surfaceView.getLayoutParams();
                lp.height =surfaceHeight ;
                lp.width = LayoutParams.MATCH_PARENT;
                surfaceView.setLayoutParams(lp);
                String VideoUrl ;
                mvideoinfo =  (VideoInfo) intent.getSerializableExtra("VideoInfo");
                System.out.println("-------------classinfo.getTeacherUrl() "+mvideoinfo.getTeacherUrl());
                media = new Media(libvlc,Uri.parse(mvideoinfo.getTeacherUrl()));


//                if (intent.getStringExtra("VideoType").equals("Local")) {
//                    media = new Media(libvlc, intent.getStringExtra("VideoUrl"));
//                } else {
//                    media = new Media(libvlc, Uri.parse(intent.getStringExtra("VideoUrl")));
//                }
            }
            else
            {
                media = new Media(libvlc, Uri.parse(mRes.getResUrl()));
                tvTitle.setText(mRes.getResName());
                switchFullScreen();
            }




            //设置监听
            mediaPlayer.setMedia(media);
            mediaPlayer.setEventListener(eventListener);
//            seekBarVolume.setOnSeekBarChangeListener(onVolumeSeekBarChangeListener);
            m_ivFullScreen.setOnClickListener(this);

            mediaPlayer.play();
        } catch (Exception e) {
            Log.e("VideoPlayer", e.toString());
        }`

**Comment by mengzhidaren** [comment]
在你主工程的build.gradle的android标签里  加入ndk   你百度下就明白了  我sdk里的代码有一半是 官方源码 所以问题不是很多  你要自定义就慢慢优化吧

**Comment by FrankLove** [comment]
@mengzhidaren 好的，谢谢，还有个问题想请教下，我直接使用libvlc这个module时，没有通过compile来使用。因为我想修改里面的一些东西。然后 发现在播放视频的时候会一直有这个打印，根本停不下来，请问这个打印是在哪输出的呢，怎么关闭呢？
12-21 09:09:46.317 30777-31313/videolist.yyl.com.vlc_sdk_lib D/TrackUtils: setParameter success for usecase = USECASE_PCM_PLAYBACK
12-21 09:09:46.327 30777-31313/videolist.yyl.com.vlc_sdk_lib D/TrackUtils: setFastFlag - flags b4 = 0 , streamType = 3
12-21 09:09:46.327 30777-31313/videolist.yyl.com.vlc_sdk_lib D/TrackUtils: Stream not ringtones/Alarm/Notification/system            sound/enforced audible
12-21 09:09:46.327 30777-31313/videolist.yyl.com.vlc_sdk_lib D/TrackUtils: setFastFlags after = 0
12-21 09:09:46.327 30777-31313/videolist.yyl.com.vlc_sdk_lib D/TrackUtils: livesLocally  = 0
12-21 09:09:46.327 30777-31313/videolist.yyl.com.vlc_sdk_lib D/TrackUtils: USECASE_PCM_PLAYBACK
12-21 09:09:46.337 30777-31313/videolist.yyl.com.vlc_sdk_lib D/TrackUtils: setParameter success for usecase = USECASE_PCM_PLAYBACK
12-21 09:09:46.357 30777-31313/videolist.yyl.com.vlc_sdk_lib D/TrackUtils: livesLocally  = 0
12-21 09:09:46.357 30777-31313/videolist.yyl.com.vlc_sdk_lib D/TrackUtils: USECASE_PCM_PLAYBACK
12-21 09:09:46.357 30777-31313/videolist.yyl.com.vlc_sdk_lib D/TrackUtils: setParameter success for usecase = USECASE_PCM_PLAYBACK
12-21 09:09:46.357 30777-31313/videolist.yyl.com.vlc_sdk_lib D/TrackUtils: setFastFlag - flags b4 = 0 , streamType = 3

**Comment by mengzhidaren** [comment]
options.add("-v"); // log输出level 
buffer 为0原因说不清 可能不支持的格式或者出错了   等我有时间统一解决

**Comment by FrankLove** [comment]
@mengzhidaren  请问 options.add("-v"); // log输出level 是什么意思呢，我想关闭改怎么做呢？
晚上测试的时候发现一个问题，就是VlcVideoView 这个控件如果我指定高度的话，会有些问题，我的测试设备是1280*720 视频文件是640*480 如果我指定了控件的高度为600px，也就是按照4:3的宽高比，那么视频播放的时候画面会出现一些重影，但是旋转为横屏的话又正常，再转为竖屏又会这样。如果不指定高度按默认math_paranet的话是正常的。如果控件指定高度按16:9 设置为450的话又不会，不知道什么原因

**Comment by mengzhidaren** [comment]
在libvlc里传ffmpeg参数的  如果不明白不用理会也没事，
关于视频高度 是ui层控制surface的实现，有问题就多看源码解吧
