### ISSUE TITLE
能实现多路rtsp流视频播放吗？

### ISSUE THREAD

**Issue by zhy060307** [mengzhidaren/Vlc-sdk-lib#21]
我用了VlcVideoView 想实现多路播放rtsp视频监控摄像头，但每次加载出来显示视频的个数不一致，有时一路，有时2路，还有时一路视频也加载不出来

**Comment by mengzhidaren** [comment]
要把我自定义的VlcVideoPlayer中的单例删除掉  或者每次new一个MediaPlayer

**Comment by zhy060307** [comment]
我再VlcVideoPlayer类设计了 isInstance为false
private static boolean isInstance = false;//是否单例播放   默认开
private static boolean isSaveState;//跳转界面时 信息保存
再VlcVideoView了的init()中设置false, 但结果还是一样，不起作用呀
   videoMediaLogic = new VlcVideoPlayer(context);
        videoMediaLogic.setVideoSizeChange(this);
        videoMediaLogic.setInstance(false);

**Comment by mengzhidaren** [comment]
我先试下 过两天上传demo
