### ISSUE TITLE
播放在线flv文件突然停止

### ISSUE THREAD

**Issue by FrankLove** [mengzhidaren/Vlc-sdk-lib#24]
测试播放在线的flv文件时，加载成功播放出画面后，有时候过了几秒钟突然停止(最多不会超过4s)，然后重新加载多次都是相同的情况，有时连续播放十几次这个flv文件也没问题，不知道是什么原因。下面是日志
12-22 20:53:16.676 6514-7728/com.lancoo.coursecenter W/VLC: [61711f18/1e30] avcodec decoder: cannot decode one frame (232 bytes)
12-22 20:53:16.706 6514-7721/com.lancoo.coursecenter D/VLC: [61381840/1e29] core vout display: auto hiding mouse cursor
12-22 20:53:16.716 6514-7684/com.lancoo.coursecenter W/VLC: [6341ec08/1e04] mp4 demux: track[0x2] will be disabled (eof?): Failed to read 284 bytes sample at 153052
12-22 20:53:16.716 6514-7728/com.lancoo.coursecenter D/dalvikvm: threadid=29: thread exiting, not yet detached (count=0)
12-22 20:53:16.726 6514-7684/com.lancoo.coursecenter D/VLC: [61711f18/1e04] core decoder: killing decoder fourcc `mp4a', 0 PES in FIFO
12-22 20:53:16.726 6514-7684/com.lancoo.coursecenter D/VLC: [61711f18/1e04] core decoder: removing module "avcodec"
12-22 20:53:16.726 6514-7684/com.lancoo.coursecenter D/VLC: [61711f18/1e04] avcodec decoder: ffmpeg codec (aac) stopped
12-22 20:53:16.746 6514-7684/com.lancoo.coursecenter D/VLC: [61d31d38/1e04] core audio resampler: removing module "ugly"
12-22 20:53:16.746 6514-7684/com.lancoo.coursecenter D/VLC: [61d29300/1e04] core audio filter: removing module "scaletempo"
12-22 20:53:16.746 6514-7684/com.lancoo.coursecenter D/VLC: [61d309b8/1e04] core audio converter: removing module "audio_format"
12-22 20:53:16.746 6514-7684/com.lancoo.coursecenter D/TrackUtils: livesLocally  = 0
12-22 20:53:16.756 6514-7684/com.lancoo.coursecenter D/TrackUtils: USECASE_PCM_PLAYBACK
12-22 20:53:16.756 6514-7684/com.lancoo.coursecenter D/TrackUtils: setParameter success for usecase = USECASE_PCM_PLAYBACK
12-22 20:53:16.756 6514-7684/com.lancoo.coursecenter D/VLC: [63682598/1e04] core volume: removing module "integer_mixer"
12-22 20:53:16.756 6514-7684/com.lancoo.coursecenter D/VLC: [61327b98/1e04] core generic: keeping audio output
12-22 20:53:16.756 6514-7684/com.lancoo.coursecenter D/VLC: [613bf860/1e04] core input: EOF reached
12-22 20:53:16.766 6514-7684/com.lancoo.coursecenter D/VLC: [613bf860/1e04] core input: waiting decoder fifos to empty
12-22 20:53:16.866 6514-7684/com.lancoo.coursecenter D/VLC: [613bf860/1e04] core input: waiting decoder fifos to empty
12-22 20:53:16.966 6514-7684/com.lancoo.coursecenter D/VLC: [613bf860/1e04] core input: waiting decoder fifos to empty
12-22 20:53:17.066 6514-7684/com.lancoo.coursecenter D/VLC: [613bf860/1e04] core input: waiting decoder fifos to empty
12-22 20:53:17.166 6514-7684/com.lancoo.coursecenter D/VLC: [613bf860/1e04] core input: waiting decoder fifos to empty
12-22 20:53:17.276 6514-7684/com.lancoo.coursecenter D/VLC: [613bf860/1e04] core input: waiting decoder fifos to empty
12-22 20:53:17.366 6514-7684/com.lancoo.coursecenter D/VLC: [613bf860/1e04] core input: waiting decoder fifos to empty
12-22 20:53:17.476 6514-7684/com.lancoo.coursecenter D/VLC: [613bf860/1e04] core input: waiting decoder fifos to empty
12-22 20:53:17.556 6514-7727/com.lancoo.coursecenter E/VLC: [6383f380/1e2f] mediacodec decoder: Decoder is draining
12-22 20:53:17.576 6514-7684/com.lancoo.coursecenter D/VLC: [613bf860/1e04] core input: waiting decoder fifos to empty
12-22 20:53:17.586 6514-7727/com.lancoo.coursecenter W/VLC: [6383f380/1e2f] mediacodec decoder: EOS sent, waiting for OutThread
12-22 20:53:17.666 6514-7684/com.lancoo.coursecenter D/VLC: [613bf860/1e04] core input: waiting decoder fifos to empty
                                                            
                                                            [ 12-22 20:53:17.716   334: 7724 E/         ]
                                                            ERROR: In boolean H264_Utils::extract_rbsp(OMX_U8*, OMX_U32, OMX_U32, OMX_U8*, OMX_U32*, NALU*)() - line 260
                                                            
                                                            [ 12-22 20:53:17.716   334: 7724 E/         ]
                                                            ERROR: In bool H264_Utils::isNewFrame(OMX_BUFFERHEADERTYPE*, OMX_U32, OMX_BOOL&)() - extract_rbsp() failed
                                                            
                                                            [ 12-22 20:53:17.756   334: 7724 E/         ]
                                                            EOS with zero length recieved
12-22 20:53:17.766 6514-7684/com.lancoo.coursecenter D/VLC: [613bf860/1e04] core input: waiting decoder fifos to empty
12-22 20:53:17.866 6514-7684/com.lancoo.coursecenter D/VLC: [613bf860/1e04] core input: waiting decoder fifos to empty
12-22 20:53:17.976 6514-7684/com.lancoo.coursecenter D/VLC: [613bf860/1e04] core input: waiting decoder fifos to empty
12-22 20:53:18.026 6514-7726/com.lancoo.coursecenter W/VLC: [6383f380/1e2e] mediacodec decoder: EOS received, abort OutThread
12-22 20:53:18.026 6514-7726/com.lancoo.coursecenter W/VLC: [6383f380/1e2e] mediacodec decoder: OutThread stopped
12-22 20:53:18.036 6514-7726/com.lancoo.coursecenter D/dalvikvm: threadid=28: thread exiting, not yet detached (count=0)
12-22 20:53:18.076 6514-7684/com.lancoo.coursecenter D/VLC: [613bf860/1e04] core input: waiting decoder fifos to empty
12-22 20:53:18.206 6514-7684/com.lancoo.coursecenter D/VLC: [613bf860/1e04] core input: waiting decoder fifos to empty
12-22 20:53:18.216 6514-7721/com.lancoo.coursecenter D/VLC: [6341bae8/1e29] core video output: picture might be displayed late (missing 7 ms)
12-22 20:53:18.306 6514-7684/com.lancoo.coursecenter D/VLC: [613bf860/1e04] core input: waiting decoder fifos to empty
12-22 20:53:18.426 6514-7684/com.lancoo.coursecenter D/VLC: [613bf860/1e04] core input: waiting decoder fifos to empty
12-22 20:53:18.516 6514-7684/com.lancoo.coursecenter D/VLC: [613bf860/1e04] core input: waiting decoder fifos to empty
12-22 20:53:18.616 6514-6514/com.lancoo.coursecenter I/System.out: ----------------EndReached 
12-22 20:53:18.616 6514-7727/com.lancoo.coursecenter D/dalvikvm: threadid=27: thread exiting, not yet detached (count=0)
12-22 20:53:18.626 6514-7684/com.lancoo.coursecenter D/VLC: [6383f380/1e04] core decoder: killing decoder fourcc `h264', 0 PES in FIFO
12-22 20:53:18.626 6514-7684/com.lancoo.coursecenter D/VLC: [6383f380/1e04] core decoder: removing module "mediacodec"
12-22 20:53:18.756 6514-7722/com.lancoo.coursecenter D/ResourceManager: ResetParameter - useCase =, useCaseFlag = 0, codecFlags = 0
12-22 20:53:18.766 6514-7684/com.lancoo.coursecenter D/VLC: [6383f380/1e04] mediacodec decoder: MediaCodec via JNI closed
12-22 20:53:18.766 6514-7684/com.lancoo.coursecenter D/VLC: [61327b98/1e04] core generic: saving a free vout
12-22 20:53:18.766 6514-7684/com.lancoo.coursecenter D/VLC: [61327b98/1e04] core generic: reusing provided vout
12-22 20:53:18.776 6514-7684/com.lancoo.coursecenter D/VLC: [6341ec08/1e04] core demux: removing module "mp4"
12-22 20:53:18.776 6514-7684/com.lancoo.coursecenter D/VLC: [6341ec08/1e04] mp4 demux: freeing all memory
12-22 20:53:18.776 6514-7721/com.lancoo.coursecenter E/VLC: [61381840/1e29] core vout display: Failed to change zoom
12-22 20:53:18.776 6514-7721/com.lancoo.coursecenter D/VLC: [61381840/1e29] android_window vout display: change source crop/aspect
12-22 20:53:18.776 6514-7684/com.lancoo.coursecenter D/VLC: [613bf860/1e04] core input: Program doesn't contain anymore ES
12-22 20:53:18.776 6514-7684/com.lancoo.coursecenter D/VLC: [614246a8/1e04] core stream: removing module "record"
12-22 20:53:18.786 6514-7684/com.lancoo.coursecenter D/VLC: [613a5580/1e04] core stream: removing module "prefetch"
12-22 20:53:18.786 6514-7684/com.lancoo.coursecenter D/VLC: [614244c8/1e04] core stream: removing module "access"
12-22 20:53:18.786 6514-7684/com.lancoo.coursecenter D/dalvikvm: threadid=25: thread exiting, not yet detached (count=0)
12-22 20:53:18.786 6514-6514/com.lancoo.coursecenter D/VLC: [613bf860/1972] core input: Destroying the input for 'Math.flv'
12-22 20:53:18.796 6514-6514/com.lancoo.coursecenter D/VLC: [613b8880/1972] core audio output: removing module "opensles_android"
12-22 20:53:18.796 6514-6514/com.lancoo.coursecenter D/VLC: [6341bae8/1972] core video output: destroying useless vout
12-22 20:53:18.796 6514-7721/com.lancoo.coursecenter D/VLC: [61381840/1e29] core vout display: removing module "android_window"
12-22 20:53:18.796 6514-7721/com.lancoo.coursecenter D/dalvikvm: threadid=26: thread exiting, not yet detached (count=0)
12-22 20:53:18.796 6514-6514/com.lancoo.coursecenter D/VLC: [63694c68/1972] core spu text: removing module "freetype"
12-22 20:53:18.796 6514-6514/com.lancoo.coursecenter D/VLC: [616b0398/1972] core scale: removing module "yuvp"
12-22 20:53:18.796 6514-6514/com.lancoo.coursecenter D/VLC: [63697578/1972] core scale: removing module "swscale"
12-22 20:53:18.826 6514-6514/com.lancoo.coursecenter I/System.out: ----------------Stopped

**Comment by mengzhidaren** [comment]
最好在电脑上用官方的VLC播放器测试视频，如果没问题在用android播放，如果还有问题只能等我有空时在编新版本了

**Comment by FrankLove** [comment]
@mengzhidaren 这个flv文件，我在手机上用其他的播放器是没有问题的，用官方的demo也没有问题。所以觉得很奇怪了。
