### ISSUE TITLE
使用进行播放RTSP流出现 buffer deadlock prevented

### ISSUE THREAD

**Issue by JacobRachel** [mengzhidaren/Vlc-sdk-lib#25]
我使用这个库时，进行播放RTSP流出现buffer deadlock prevented，播放失败，能够帮我看看吗，
RTSP流信息发布在公网上;rtsp://139.199.159.71:554/easypusher_rtsp.sdp    ,我用windows上的vlc能够播放

**Comment by mengzhidaren** [comment]
你这地址我试了下  用的三星手机  没问题 流畅播放

**Comment by l179224710** [comment]
这个我自己解决了，当出现buffer 未获得时，对流进行处理，发包的速率降低就可以解决

**Comment by l179224710** [comment]
还有一个问题，播放过了一会儿获取流数据会停止，如何加个判断那，当数据流没有时重新发送请求数据

**Comment by l179224710** [comment]
还有一个问题，播放过了一会儿获取流数据会停止，如何加个判断那，当数据流没有时重新发送请求数据

**Comment by mengzhidaren** [comment]
Media.EventListener接口 应该能监听到的 你自已慢慢调试吧

在 2017年1月12日 下午3:08，l179224710 <notifications@github.com>写道：

**Comment by l179224710** [comment]
好的~
