### ISSUE TITLE
java.lang.UnsatisfiedLinkError:

### ISSUE THREAD

**Issue by bifan-wei** [mengzhidaren/Vlc-sdk-lib#26]
整理到eclipse工程下报这个错误：
java.lang.UnsatisfiedLinkError: Couldn't load c++_shared from loader dalvik.system.PathClassLoader[DexPathList[[zip file "/data/app/com.hw.vlcplayer-1.apk"],nativeLibraryDirectories=[/data/app-lib/com.hw.vlcplayer-1, /vendor/lib, /data/cust/lib, /system/lib, /data/datalib]]]: findLibrary returned null

应该是找不到so库，不大会，请教一下大神。

**Comment by mengzhidaren** [comment]
你是新手吧  建议你把工程迁移到android studio里面去   早晚要迁的
