### ISSUE TITLE
倍速播放杂音太大

### ISSUE THREAD

**Issue by jackiesea** [mengzhidaren/Vlc-sdk-lib#29]
如题，设置2倍速度播放，杂音太大，完全听不到，vlc原生播放正常。

**Comment by mengzhidaren** [comment]
我在忙别的 你得等段时间了，有空我在编新版本

**Comment by jackiesea** [comment]
已经找到可移植版本了，感谢。

**Comment by csh159** [comment]
@jackiesea 能提供一下你的移植版本么？现在也遇到了这种情况

**Comment by jackiesea** [comment]
@csh159 
VLCOptions类中，
final boolean timeStreching = pref.getBoolean("enable_time_stretching_audio", true);
传入“true”，打开这个功能需要硬件支持，不过目前手机的硬件配置几乎都是没问题的。

**Comment by csh159** [comment]
@jackiesea 谢谢啊，用你的方法解决了！为啥用这里面的libvlc里面的源码改然后用sdk里面的so会崩掉，我现在是反编译改了再放进去！
