### ISSUE TITLE
播放rtsp延时怎么降低呢

### ISSUE THREAD

**Issue by roger66** [mengzhidaren/Vlc-sdk-lib#3]

**Comment by mengzhidaren** [comment]
我还没用这个播放器做过直播 ，
可以给你个参考，
在配置参数里设置
options.add("RV16");//清晰度
 options.add("--network-caching=" + networkCaching);//缓冲
或者 传入其它的ffmpeg的参数 https://wiki.videolan.org/VLC_command-line_help
