### ISSUE TITLE
目前支持的库问题

### ISSUE THREAD

**Issue by bifan-wei** [mengzhidaren/Vlc-sdk-lib#31]
目前支持的库： x86_64 x86 armeabi-v7a arm64-v8a mips mips64 *目前的功能，只找到这个文件夹armeabi-v7a，请问还要自己去编译或者下载么？

**Comment by mengzhidaren** [comment]
你拉取下我上一次我提交的代码 里面有   最新版改动太多 还没提库呢

**Comment by zackle** [comment]
seekto  现在不能工作么？我现在在做媒体播放的指定位置 和拖拉进度播放  这个方法不起作用      mMediaPlayer.setTime(pos);  mMediaPlayer.setPosition(pos); mMediaPlayer.setPosition((float) pos / (float) getDuration()); 三个方法都试了 到这步 跟不到代码了 在线等

**Comment by mengzhidaren** [comment]
如果服务器支持的话这个库是没问题的 ，  所有的直播流是不支持seek的，可以用demo地址测试

**Comment by zackle** [comment]
我现在在做一个播放器 但是不是直播 是播放电影用的 播放ts流  服务器是支持 seek 的 只不过现在 android原来的不支持 这个播放格式 所以 有么有什么办法 可以能seek

**Comment by zackle** [comment]
冒昧的问一下 可以看看你的源码么?我自己编译一下 看看问题在哪里 谢谢

**Comment by zackle** [comment]
441619630 这个是我的QQ方便的话 可以加下方便即时通信么

**Comment by mengzhidaren** [comment]
源码太大了发不了你 至少10个G  主要是依赖环境有点多  273518021

**Comment by bifan-wei** [comment]
嗯嗯，谢谢回复。我用了你上一次提交的，可以用，只是有点问题，有些视频刚开始加载时会不断重试加载，就是不断调取buffering那里，有时进度从0到100这样不断这样循环，感觉是失败了不断在重试，我用了官方pc的测试，没有问题，想了很久都不知道怎么改善。

**Comment by bifan-wei** [comment]
大神，如果方便的话，能不能把其他的so库也提交下，想换你现在的新版本试一试。。。
