### ISSUE TITLE
视频在播完之后会有大概1秒的黑屏时间

### ISSUE THREAD

**Issue by mlhaobo** [mengzhidaren/Vlc-sdk-lib#32]
本地视频在播完之后重新再播放的时候会有大概1秒的黑屏时间，请问这个要怎么解决呢？还有我这边想拿到本地视频的每一帧数据，textureView里面是有getbitmap方法，但是要是实时取的话只要分辨率一大效率就会明显降低，有没有什么办法能拿到每一帧的数据的buffer呢？

**Comment by mengzhidaren** [comment]
1秒黑屏是我在java层扩展的方法，你要更好的效果就在native重写loop方法。每一帧的buffer我也没写过不清楚

**Comment by mlhaobo** [comment]
在java层扩展的方法是写在什么地方呢？VlcVideoPlayer类和VlcVideoView类中的setLoop方法里面都没有内容

**Comment by mlhaobo** [comment]
是onEventNative里面的延时吗？能不能指点下怎么不做延时播放

**Comment by mengzhidaren** [comment]
-R, --repeat  和-L, --loop  你自已调试吧
