### ISSUE TITLE
在线视频加载退出卡住

### ISSUE THREAD

**Issue by jackiesea** [mengzhidaren/Vlc-sdk-lib#34]
播放在线视频，如果一进入播放，因为网络不良好或者视频链接服务器问题加载较慢，当视频还没渲染好，退出播放回到上一层，app会卡住等一会才恢复正常。跟踪发现是卡在了release（）的mMediaPlayer.stop();处，最终调用底层的nativeStop（）。大神帮看下，而且这个stop调用好像还只能放在主线程。（可能不太好测试这个问题）

**Comment by mengzhidaren** [comment]
这个问题我知道  官方里有这个bug   在释放资源时 会阻塞mainlooper 你可到官方issues提bug

**Comment by whbharvey** [comment]
你好，我也遇到这个问题，有人知道怎么解决吗？
