### ISSUE TITLE
问一下怎么播放在线MP3

### ISSUE THREAD

**Issue by csh159** [mengzhidaren/Vlc-sdk-lib#36]
E/VLC: [e2313228/f8b] core input source: cannot parse http://172.19.2.26:3000/voiceFiles/201704/20101-1491358051902.mp3
04-05 10:25:47.088 3637-3979/com.jxnews.monitor E/VLC: [de09c9e8/f8b] core input: Your input can't be opened

**Comment by mengzhidaren** [comment]
在我的demo里打开试下  应该不会有问题的

**Comment by csh159** [comment]
问一下MediaPlayer播放完成有接口或者方法么？
