### ISSUE TITLE
播放本地720P视频，刚开始播放，会卡顿6秒 左右，接着正常，一般是什么问题呢？

### ISSUE THREAD

**Issue by jiuguo2007** [mengzhidaren/Vlc-sdk-lib#4]
播放本地720P视频，刚开始播放，会卡顿6秒 左右，接着正常，一般是什么问题呢？

**Comment by mengzhidaren** [comment]
final Media media = new Media(libVLC, path);
media.setHWDecoderEnabled(false, false);
media.parseAsync(Media.Parse.FetchLocal);
你可以尝试关闭硬件加速 使用软解  在低端机上很有效果

**Comment by jiuguo2007** [comment]
两个false更卡了，而且这个vlc库在部分机器上，播放视频老是提示permission denide，但清单文件已经放开了读取内存的权限，求大神指点，QQ：151774265，付费也可。

**Comment by mengzhidaren** [comment]
我在云测上试过720P的视频，目前100%通过的，没有你说的这些问题，你说的权限的问题 和播放器没关系，软解卡顿原因很多种，要一点点调校的，我QQ273518021
