### ISSUE TITLE
局域网的rtsp无法播放

### ISSUE THREAD

**Issue by wangmubiao** [mengzhidaren/Vlc-sdk-lib#41]
我的一个局域网编码器码流地址：rtsp://192.168.1.168/0，用现在这个vlc项目，播放不了。不知道什么原因，试了好多法子都解决不了。哪位大神指点一下，不胜感激。
logcat导出：
05-26 16:22:17.642 11666-11932/org.videolan.java_sample E/VLC: [a281f2c8/2e9c] cache_read stream: cannot pre fill buffer
05-26 16:22:17.644 11666-11932/org.videolan.java_sample E/VLC: [b4bbb488/2e9c] xml xml reader: XML parser error (line 1) : Extra content at the end of the document
05-26 16:22:17.645 11666-11932/org.videolan.java_sample E/VLC: [a281f2c8/2e9c] cache_read stream: cannot pre fill buffer
05-26 16:22:17.646 11666-11932/org.videolan.java_sample E/VLC: [b4bbb488/2e9c] xml xml reader: XML parser error (line 1) : Extra content at the end of the document
05-26 16:22:17.647 11666-11932/org.videolan.java_sample E/VLC: [a281f228/2e9c] filesystem stream: cannot open file /vendor/etc/fallback_fonts.xml (No such file or directory)
05-26 16:22:17.647 11666-11932/org.videolan.java_sample E/VLC: [a281f228/2e9c] core stream: File reading failed
05-26 16:22:17.647 11666-11932/org.videolan.java_sample E/VLC: [a281f228/2e9c] core stream: VLC could not open the file "/vendor/etc/fallback_fonts.xml" (No such file or directory).
05-26 16:22:17.647 11666-11932/org.videolan.java_sample E/VLC: [b49b8b28/2e9c] core spu text: no suitable access module for `file:///vendor/etc/fallback_fonts.xml'
05-26 16:22:17.659 11666-11942/org.videolan.java_sample E/VLC: [a28788f8/2ea6] android_window window: request 1 not implemented
05-26 16:22:17.670 11666-11942/org.videolan.java_sample E/VLC: [a28788f8/2ea6] android_window window: request 0 not implemented
05-26 16:22:17.670 11666-11942/org.videolan.java_sample E/VLC: [a28788f8/2ea6] android_window window: request 0 not implemented
05-26 16:22:17.671 11666-11942/org.videolan.java_sample E/VLC: [b489cae8/2ea6] core vout display: Failed to change zoom
05-26 16:22:17.671 11666-11942/org.videolan.java_sample E/VLC: [b489cae8/2ea6] core vout display: Failed to change Viewpoint
05-26 16:22:17.671 11666-11942/org.videolan.java_sample E/VLC: [a28788f8/2ea6] android_window window: request 1 not implemented
05-26 16:22:17.673 11666-11932/org.videolan.java_sample E/VLC: [a281f868/2e9c] cache_read stream: cannot pre fill buffer
05-26 16:22:17.673 11666-11932/org.videolan.java_sample E/VLC: [b4bbb488/2e9c] xml xml reader: XML parser error (line 1) : Extra content at the end of the document
05-26 16:22:17.674 11666-11932/org.videolan.java_sample E/VLC: [a281f868/2e9c] cache_read stream: cannot pre fill buffer
05-26 16:22:17.675 11666-11932/org.videolan.java_sample E/VLC: [b4bbb488/2e9c] xml xml reader: XML parser error (line 1) : Extra content at the end of the document
05-26 16:22:17.675 11666-11932/org.videolan.java_sample E/VLC: [a281f548/2e9c] filesystem stream: cannot open file /vendor/etc/fallback_fonts.xml (No such file or directory)
05-26 16:22:17.676 11666-11932/org.videolan.java_sample E/VLC: [a281f548/2e9c] core stream: File reading failed
05-26 16:22:17.676 11666-11932/org.videolan.java_sample E/VLC: [a281f548/2e9c] core stream: VLC could not open the file "/vendor/etc/fallback_fonts.xml" (No such file or directory).
05-26 16:22:17.676 11666-11932/org.videolan.java_sample E/VLC: [b49b8b28/2e9c] core spu text: no suitable access module for `file:///vendor/etc/fallback_fonts.xml'
05-26 16:22:17.682 11666-11944/org.videolan.java_sample I/OMXClient: Using client-side OMX mux.
05-26 16:22:17.700 11666-11944/org.videolan.java_sample E/ACodec: [OMX.NX.VIDEO_DECODER.avc] storeMetaDataInBuffers failed w/ err -1010
05-26 16:22:17.752 11666-11942/org.videolan.java_sample E/VLC: [a28788f8/2ea6] android_window window: request 0 not implemented
05-26 16:22:17.752 11666-11942/org.videolan.java_sample E/VLC: [a28788f8/2ea6] android_window window: request 0 not implemented
05-26 16:22:17.755 11666-11932/org.videolan.java_sample W/art: Native thread exiting without having called DetachCurrentThread (maybe it's going to use a pthread_key_create destructor?): Thread[17,tid=11932,Native,Thread*=0xb4b45000,peer=0x12d440a0,"VlcObject"]
05-26 16:22:17.757 11666-11942/org.videolan.java_sample E/[EGL-ERROR]: EGLBoolean __egl_platform_create_surface_window(egl_surface*, mali_base_ctx_handle):933: =========> usage 0x900
05-26 16:22:17.769 11666-11942/org.videolan.java_sample W/art: Native thread exiting without having called DetachCurrentThread (maybe it's going to use a pthread_key_create destructor?): Thread[18,tid=11942,Native,Thread*=0xb4836800,peer=0x12d940a0,"AWindowHandler"]
05-26 16:22:17.771 11666-11666/org.videolan.java_sample I/Choreographer: Skipped 36 frames!  The application may be doing too much work on its main thread.
05-26 16:22:28.673 11666-11666/org.videolan.java_sample E/lala: onSurfaceDestroyed
05-26 16:22:29.019 11666-12093/org.videolan.java_sample W/VideoCapabilities: Unsupported profile 4 for video/avc
05-26 16:22:29.019 11666-12093/org.videolan.java_sample W/VideoCapabilities: Unsupported profile 4 for video/avc
05-26 16:22:29.019 11666-12093/org.videolan.java_sample W/VideoCapabilities: Unsupported profile 4 for video/avc
05-26 16:22:29.019 11666-12093/org.videolan.java_sample W/VideoCapabilities: Unsupported profile 32 for video/avc
05-26 16:22:29.019 11666-12093/org.videolan.java_sample W/VideoCapabilities: Unsupported profile 32 for video/avc
05-26 16:22:29.019 11666-12093/org.videolan.java_sample W/VideoCapabilities: Unsupported profile 32 for video/avc
05-26 16:22:29.019 11666-12093/org.videolan.java_sample W/VideoCapabilities: Unsupported profile 64 for video/avc
05-26 16:22:29.019 11666-12093/org.videolan.java_sample W/VideoCapabilities: Unsupported profile 64 for video/avc
05-26 16:22:29.019 11666-12093/org.videolan.java_sample W/VideoCapabilities: Unsupported profile 64 for video/avc
05-26 16:22:29.019 11666-12093/org.videolan.java_sample W/VideoCapabilities: Unrecognized profile 128 for video/avc
05-26 16:22:29.019 11666-12093/org.videolan.java_sample W/VideoCapabilities: Unrecognized profile 128 for video/avc
05-26 16:22:29.020 11666-12093/org.videolan.java_sample W/VideoCapabilities: Unrecognized profile 128 for video/avc
05-26 16:22:29.020 11666-12093/org.videolan.java_sample W/VideoCapabilities: Unrecognized profile 256 for video/avc
05-26 16:22:29.020 11666-12093/org.videolan.java_sample W/VideoCapabilities: Unrecognized profile 256 for video/avc
05-26 16:22:29.020 11666-12093/org.videolan.java_sample W/VideoCapabilities: Unrecognized profile 256 for video/avc
05-26 16:22:29.020 11666-12093/org.videolan.java_sample W/VideoCapabilities: Unrecognized profile 512 for video/avc
05-26 16:22:29.020 11666-12093/org.videolan.java_sample W/VideoCapabilities: Unrecognized profile 512 for video/avc
05-26 16:22:29.020 11666-12093/org.videolan.java_sample W/VideoCapabilities: Unrecognized profile 512 for video/avc
05-26 16:22:29.020 11666-12093/org.videolan.java_sample W/VideoCapabilities: Unrecognized profile 1024 for video/avc
05-26 16:22:29.020 11666-12093/org.videolan.java_sample W/VideoCapabilities: Unrecognized profile 1024 for video/avc
05-26 16:22:29.020 11666-12093/org.videolan.java_sample W/VideoCapabilities: Unrecognized profile 1024 for video/avc
05-26 16:22:29.029 11666-12093/org.videolan.java_sample E/VLC: [a281f908/2f3d] cache_read stream: cannot pre fill buffer
05-26 16:22:29.031 11666-12093/org.videolan.java_sample E/VLC: [a2882128/2f3d] xml xml reader: XML parser error (line 1) : Extra content at the end of the document
05-26 16:22:29.032 11666-12093/org.videolan.java_sample E/VLC: [a281f908/2f3d] cache_read stream: cannot pre fill buffer
05-26 16:22:29.033 11666-12093/org.videolan.java_sample E/VLC: [a2882128/2f3d] xml xml reader: XML parser error (line 1) : Extra content at the end of the document
05-26 16:22:29.034 11666-12093/org.videolan.java_sample E/VLC: [a281f868/2f3d] filesystem stream: cannot open file /vendor/etc/fallback_fonts.xml (No such file or directory)
05-26 16:22:29.034 11666-12093/org.videolan.java_sample E/VLC: [a281f868/2f3d] core stream: File reading failed
05-26 16:22:29.035 11666-12093/org.videolan.java_sample E/VLC: [a281f868/2f3d] core stream: VLC could not open the file "/vendor/etc/fallback_fonts.xml" (No such file or directory).
05-26 16:22:29.035 11666-12093/org.videolan.java_sample E/VLC: [a28282a8/2f3d] core spu text: no suitable access module for `file:///vendor/etc/fallback_fonts.xml'
05-26 16:22:29.048 11666-12129/org.videolan.java_sample E/VLC: [a2879848/2f61] android_window window: request 1 not implemented
05-26 16:22:29.048 11666-12129/org.videolan.java_sample E/VLC: [a2879848/2f61] android_window window: request 1 not implemented
05-26 16:22:29.051 11666-12093/org.videolan.java_sample E/VLC: [b488cf28/2f3d] core video output: video output creation failed
05-26 16:22:29.051 11666-12129/org.videolan.java_sample W/art: Native thread exiting without having called DetachCurrentThread (maybe it's going to use a pthread_key_create destructor?): Thread[18,tid=12129,Native,Thread*=0xb4b47000,peer=0x12deb100,"AWindowHandler"]
05-26 16:22:29.053 11666-12093/org.videolan.java_sample E/VLC: [b49b7d28/2f3d] core decoder: failed to create video output
05-26 16:22:29.053 11666-12093/org.videolan.java_sample E/VLC: [b49b7d28/2f3d] mediacodec decoder: Opaque Vout request failed
05-26 16:22:29.070 11666-12093/org.videolan.java_sample W/art: Native thread exiting without having called DetachCurrentThread (maybe it's going to use a pthread_key_create destructor?): Thread[17,tid=12093,Native,Thread*=0xb4836800,peer=0x12d77fa0,"VlcObject"]
05-26 16:22:36.251 11666-11691/org.videolan.java_sample E/VLC-std: Warning: option --ffmpeg-threads no longer exists.
05-26 16:22:36.314 11666-11692/org.videolan.java_sample E/[EGL-ERROR]: EGLBoolean __egl_platform_create_surface_window(egl_surface*, mali_base_ctx_handle):933: =========> usage 0x900
05-26 16:22:37.217 11666-12291/org.videolan.java_sample W/VideoCapabilities: Unsupported profile 4 for video/avc
05-26 16:22:37.217 11666-12291/org.videolan.java_sample W/VideoCapabilities: Unsupported profile 4 for video/avc
05-26 16:22:37.217 11666-12291/org.videolan.java_sample W/VideoCapabilities: Unsupported profile 4 for video/avc
05-26 16:22:37.218 11666-12291/org.videolan.java_sample W/VideoCapabilities: Unsupported profile 32 for video/avc
05-26 16:22:37.218 11666-12291/org.videolan.java_sample W/VideoCapabilities: Unsupported profile 32 for video/avc
05-26 16:22:37.218 11666-12291/org.videolan.java_sample W/VideoCapabilities: Unsupported profile 32 for video/avc
05-26 16:22:37.218 11666-12291/org.videolan.java_sample W/VideoCapabilities: Unsupported profile 64 for video/avc
05-26 16:22:37.218 11666-12291/org.videolan.java_sample W/VideoCapabilities: Unsupported profile 64 for video/avc
05-26 16:22:37.218 11666-12291/org.videolan.java_sample W/VideoCapabilities: Unsupported profile 64 for video/avc
05-26 16:22:37.218 11666-12291/org.videolan.java_sample W/VideoCapabilities: Unrecognized profile 128 for video/avc
05-26 16:22:37.218 11666-12291/org.videolan.java_sample W/VideoCapabilities: Unrecognized profile 128 for video/avc
05-26 16:22:37.219 11666-12291/org.videolan.java_sample W/VideoCapabilities: Unrecognized profile 128 for video/avc
05-26 16:22:37.219 11666-12291/org.videolan.java_sample W/VideoCapabilities: Unrecognized profile 256 for video/avc
05-26 16:22:37.219 11666-12291/org.videolan.java_sample W/VideoCapabilities: Unrecognized profile 256 for video/avc
05-26 16:22:37.219 11666-12291/org.videolan.java_sample W/VideoCapabilities: Unrecognized profile 256 for video/avc
05-26 16:22:37.219 11666-12291/org.videolan.java_sample W/VideoCapabilities: Unrecognized profile 512 for video/avc
05-26 16:22:37.219 11666-12291/org.videolan.java_sample W/VideoCapabilities: Unrecognized profile 512 for video/avc
05-26 16:22:37.219 11666-12291/org.videolan.java_sample W/VideoCapabilities: Unrecognized profile 512 for video/avc
05-26 16:22:37.219 11666-12291/org.videolan.java_sample W/VideoCapabilities: Unrecognized profile 1024 for video/avc
05-26 16:22:37.219 11666-12291/org.videolan.java_sample W/VideoCapabilities: Unrecognized profile 1024 for video/avc
05-26 16:22:37.219 11666-12291/org.videolan.java_sample W/VideoCapabilities: Unrecognized profile 1024 for video/avc
05-26 16:22:37.245 11666-12291/org.videolan.java_sample E/VLC: [a281fb88/3003] filesystem stream: cannot open file /vendor/etc/fallback_fonts.xml (No such file or directory)
05-26 16:22:37.245 11666-12291/org.videolan.java_sample E/VLC: [a281fb88/3003] core stream: File reading failed
05-26 16:22:37.245 11666-12291/org.videolan.java_sample E/VLC: [a281fb88/3003] core stream: VLC could not open the file "/vendor/etc/fallback_fonts.xml" (No such file or directory).
05-26 16:22:37.245 11666-12291/org.videolan.java_sample E/VLC: [a29200a8/3003] core spu text: no suitable access module for `file:///vendor/etc/fallback_fonts.xml'
05-26 16:22:37.249 11666-12306/org.videolan.java_sample E/VLC: [b4bb2298/3012] android_window window: request 1 not implemented
05-26 16:22:37.252 11666-12306/org.videolan.java_sample E/VLC: [b4bb2298/3012] android_window window: request 0 not implemented
05-26 16:22:37.252 11666-12306/org.videolan.java_sample E/VLC: [b4bb2298/3012] android_window window: request 0 not implemented
05-26 16:22:37.253 11666-12306/org.videolan.java_sample E/VLC: [af5158a8/3012] core vout display: Failed to change zoom
05-26 16:22:37.253 11666-12306/org.videolan.java_sample E/VLC: [af5158a8/3012] core vout display: Failed to change Viewpoint
05-26 16:22:37.253 11666-12306/org.videolan.java_sample E/VLC: [b4bb2298/3012] android_window window: request 1 not implemented
05-26 16:22:37.264 11666-12291/org.videolan.java_sample E/VLC: [a281fea8/3003] filesystem stream: cannot open file /vendor/etc/fallback_fonts.xml (No such file or directory)
05-26 16:22:37.264 11666-12291/org.videolan.java_sample E/VLC: [a281fea8/3003] core stream: File reading failed
05-26 16:22:37.264 11666-12291/org.videolan.java_sample E/VLC: [a281fea8/3003] core stream: VLC could not open the file "/vendor/etc/fallback_fonts.xml" (No such file or directory).
05-26 16:22:37.264 11666-12291/org.videolan.java_sample E/VLC: [a29200a8/3003] core spu text: no suitable access module for `file:///vendor/etc/fallback_fonts.xml'
05-26 16:22:37.268 11666-12308/org.videolan.java_sample I/OMXClient: Using client-side OMX mux.
05-26 16:22:37.287 11666-12308/org.videolan.java_sample E/ACodec: [OMX.NX.VIDEO_DECODER.avc] storeMetaDataInBuffers failed w/ err -1010
05-26 16:22:38.255 11666-12306/org.videolan.java_sample E/VLC: [b4bb2298/3012] android_window window: request 3 not implemented
05-26 16:22:39.391 11666-12316/org.videolan.java_sample E/VLC: [a291f2a8/301c] mediacodec decoder: output: 842094169 unknown, 720x576 stride 0 0, crop 0 0 0 0

**Comment by wangmubiao** [comment]
用旧版本的vlc是可以播放的，vlc官网的vlc 安卓app也可以播放。就咱们这个搞不定，搞不明白。

**Comment by buluojava** [comment]
我也遇到这个问题，有解决的办法吗？

**Comment by mengzhidaren** [comment]
最近有点忙 过两天我把全版本的库 都做出来 到时选个能用的就行了

**Comment by wangmubiao** [comment]
orz～静候大神佳音，编译实在太繁琐了，我在git上另找了一个库是可以用的，但是没有这个版本设计的好。

**Comment by buluojava** [comment]
@wangmubiao 是怎样的库我有点急让我看下，我试了十几个库也只有这个库没有延迟五秒以上的问题但却有的rtsp链接播放不了不太明白为什么

**Comment by wangmubiao** [comment]
@buluojava 急得话用这个吧https://github.com/mrmaffen/vlc-android-sdk

**Comment by buluojava** [comment]
@wangmubiao 我找到一个对我来说更好的https://github.com/CoffeeTL/rtsp，希望对你有用，测试播放C端给我的流无延迟，但直接连摄像头流会卡顿和花屏，带有截图和录像功能但我没测试。

**Comment by wangmubiao** [comment]
@buluojava 谢谢~好像这是比较旧版的（没有亲测），我之前用过旧版的，连接高清编码器，边缘会有闪烁条纹。
