### ISSUE TITLE
你是修改过 源代码吗,我用自己编译的库放在你的工程里提示缺少方法

### ISSUE THREAD

**Issue by SleepForever** [mengzhidaren/Vlc-sdk-lib#43]

**Comment by SleepForever** [comment]
no method with name='dispatchEventFromNative' signature='(IJJF)V' in class Lorg/videolan/libvlc/VLCObject;

我报的是这个错，是编译脚本改了？ 感觉不是Java层的错

**Comment by mengzhidaren** [comment]
我拉的vlc版本是2.2.0的  不一样差别很大的
