### ISSUE TITLE
在RecycleListView上出现位移

### ISSUE THREAD

**Issue by ownerHZH** [mengzhidaren/Vlc-sdk-lib#47]
在RecycleListView的上拉和加载更多的时候，点击播放，会出现视频布局上移的问题。

**Comment by mengzhidaren** [comment]
这只是个播放器库文件 和布局没关联

**Comment by jj8401** [comment]
@ownerHZH 为什么现在这个 demo 看不到 RecycleListView 这种布局呢

**Comment by jj8401** [comment]
@ownerHZH 目前的程序和首页的 gif 效果图不一样啊，能不能把之前的发我一份

**Comment by mengzhidaren** [comment]
这只是个播放器库文件  之前的布局都是临时写的现在没了   你在git历史记录里找吧
