### ISSUE TITLE
播放不出视频

### ISSUE THREAD

**Issue by lingchen52** [mengzhidaren/Vlc-sdk-lib#48]
我通过依赖compile 'com.yyl.vlc:vlc-android-sdk:1.3.0'使用你的vlc来播放hls视频，在多个设备上都播放失败，使用方式如下`    public void initVlcplayer() {

//        Media media = new Media(VLCInstance.get(this),

//                Uri.parse("http://v.tiaooo.com/ljbmVx2MrnY2NiNk-cWsUh08480y"));

//        media.setHWDecoderEnabled(true, true);

//        VLCInstance.get(this);

        mVlcVideoView.setMediaListenerEvent(new MediaControl(mVlcVideoView));

        new Handler().postDelayed(new Runnable() {

            @Override

            public void run() {

                Log.i("VideoActivity", "---------   start   ----------------");

                mVlcVideoView.startPlay(mStrings[position]);

            }

        }, 1000);

//        mVlcVideoView.setMedia(media);

    }

**Comment by lingchen52** [comment]
log如下07-25 14:33:02.788 1092-1092/com.example.test.androidtest I/VLC/LibVLC/Util: ELF ABI = arm, 32bits
07-25 14:33:02.788 1092-1092/com.example.test.androidtest I/VLC/LibVLC/Util: ELF arch = v7
07-25 14:33:02.788 1092-1092/com.example.test.androidtest I/VLC/LibVLC/Util: ELF fpu = false
07-25 14:33:02.796 1092-1092/com.example.test.androidtest W/VLC/LibVLC/Util: Could not find maximum CPU frequency!
07-25 14:33:02.796 1092-1092/com.example.test.androidtest D/VLC/LibVLC/Util: machineSpecs: hasArmV6: true, hasArmV7: true, hasX86: true, is64bits: false
07-25 14:33:02.928 1092-1092/com.example.test.androidtest D/dalvikvm: Trying to load lib /data/app-lib/com.example.test.androidtest-2/libvlc.so 0x42db6698
07-25 14:33:03.272 1092-1092/com.example.test.androidtest D/dalvikvm: Added shared lib /data/app-lib/com.example.test.androidtest-2/libvlc.so 0x42db6698
07-25 14:33:03.276 1092-1092/com.example.test.androidtest D/dalvikvm: Trying to load lib /data/app-lib/com.example.test.androidtest-2/libvlcjni.so 0x42db6698
07-25 14:33:03.276 1092-1092/com.example.test.androidtest D/dalvikvm: Added shared lib /data/app-lib/com.example.test.androidtest-2/libvlcjni.so 0x42db6698
07-25 14:33:03.276 1092-1092/com.example.test.androidtest D/VLC/JNI/VLCObject: JNI interface loaded.
07-25 14:33:04.393 1092-1200/com.example.test.androidtest E/VLC: [7923aff8/4b0] android_audiotrack audio output: GetMethodID(AudioTrack.writeV21) failed
07-25 14:33:04.393 1092-1200/com.example.test.androidtest E/VLC: [7923aff8/4b0] android_audiotrack audio output: GetStaticFieldID(AudioFormat.ENCODING_AC3) failed
07-25 14:33:04.393 1092-1200/com.example.test.androidtest E/VLC: [7923aff8/4b0] android_audiotrack audio output: GetStaticFieldID(AudioFormat.ENCODING_DTS) failed
07-25 14:33:04.393 1092-1200/com.example.test.androidtest E/VLC: [7923aff8/4b0] android_audiotrack audio output: GetStaticFieldID(AudioManager.ERROR_DEAD_OBJECT) failed

**Comment by lingchen52** [comment]
我使用的方式有问题吗？我是参考你的demo写的

**Comment by mengzhidaren** [comment]
看你log像是没成功加载.so文件       ndk { abiFilters 'armeabi-v7a' }  这里要和设备 cpu 同参  其它的问题我也看不出来
