### ISSUE TITLE
有几个问题

### ISSUE THREAD

**Issue by liupeng110** [mengzhidaren/Vlc-sdk-lib#55]
1.播放网络的文件（视频/音乐）  快进快退都会出现延迟播放 有时候会延迟4-5秒左右  
这个可以设置缓存么
2.播放本地无损音乐  ape格式的 会出现进度条的播放时间跳秒  本来应该显示  00：20的显示00：24  这样 
中间就没有更新时间    
不用view直接用mediaplay那种方式如果监听进度啊楼主  网上搜的api不太准或者老旧了都

**Comment by mengzhidaren** [comment]
看我源代码复制出来改下就行了
