### ISSUE TITLE
每次视频执行onstop或者ondestroy操作都要很长时间

### ISSUE THREAD

**Issue by daydreamty** [mengzhidaren/Vlc-sdk-lib#58]
执行onstop后，视频播放后台没有很快释放，通常需要50s以上才能释放或者停止播放器，执行了onstop之后，网络连接还在持续，没有立即断开

**Comment by jackiesea** [comment]
最新的库还有这个问题么？？

**Comment by daydreamty** [comment]
最新版的库好像很快，2s左右了吧。

**Comment by jackiesea** [comment]
嗯，试了下，缓冲过程中退出有时还会卡住无响应，特别是第一次，但比之前版本是好了好多。这个问题在官方论坛还有人在反馈。
