### ISSUE TITLE
播放的视频底部有白边

### ISSUE THREAD

**Issue by xiaos** [mengzhidaren/Vlc-sdk-lib#62]
如图所示

![2017-11-21 21_04_56-vlc-sdk-lib-master - c__users_chensz_downloads_vlc-sdk-lib-master - demo -](https://user-images.githubusercontent.com/2921946/33074024-b1466450-ceff-11e7-94ee-bdfdc38eb0df.png)

**Comment by mengzhidaren** [comment]
自已定义surfaceView适配吧
