### ISSUE TITLE
 Could not open http://.../xx.mp4,出现 Unknown error 1094995529

### ISSUE THREAD

**Issue by daydreamty** [mengzhidaren/Vlc-sdk-lib#63]
播放时出现 avformat demux: Could not open http://.../xx.mp4: Unknown error 1094995529

**Comment by mengzhidaren** [comment]
看错误是解封装出错，试下官方播放器吧，库文件我几乎没改动过的，还有问题等官方解吧

**Comment by daydreamty** [comment]
官方播放器android版我试了下播放貌似也有问题。会不会是文件过大的问题，我看这个文件有20多g

**Comment by mengzhidaren** [comment]
这个不好说   你可以把文件用ffmpeg切割成小文件试下
