### ISSUE TITLE
亲爱的大神,能不能搞一个左右声道呀?

### ISSUE THREAD

**Issue by 32ns** [mengzhidaren/Vlc-sdk-lib#65]
找了半天没找到能控制声道的函数,想自己加一个也不知道怎么搞,求大神指点!! 非常非常非常感谢!

**Comment by mengzhidaren** [comment]
如果音频有多轨道的话用setVideoTrack(int index)切换   其它的看官方API

**Comment by 32ns** [comment]
不是音轨,是左声道 右声道,搞不定,真心搞不定呀

**Comment by mengzhidaren** [comment]
我没研究过 不过看源代码在  c++里有控制左右声道    你可以自已编译源码尝试
