### ISSUE TITLE
编译相关

### ISSUE THREAD

**Issue by FSY-Specter** [mengzhidaren/Vlc-sdk-lib#7]
你好！大神
我环境中没使用export ANDROID_ABI=armeabi-v7a
NDK 用的r13用r12b会提示我使用r13
在编译的时候第一次直接sh compile.sh默认编译armeabi-v7a
我要编译其他平台支持库就出错（是不是要清理一下？）：
## sh compile.sh -a mips64
都会出现一下错误
`make: Entering directory `/home/specter/Development/vlc-android/medialibrary'
[arm64-v8a] Gdbserver      : [aarch64-linux-android] libs/arm64-v8a/gdbserver
[arm64-v8a] Gdbsetup       : libs/arm64-v8a/gdb.setup
[arm64-v8a] SharedLibrary  : libmla.so
/home/specter/Development/Android/android-ndk-r13/toolchains/aarch64-linux-android-4.9/prebuilt/linux-x86_64/lib/gcc/aarch64-linux-android/4.9.x/../../../../aarch64-linux-android/bin/ld: skipping incompatible /home/specter/Development/vlc-android/medialibrary/medialibrary/build-android/.libs/libmedialibrary.a when searching for -lmedialibrary
/home/specter/Development/Android/android-ndk-r13/toolchains/aarch64-linux-android-4.9/prebuilt/linux-x86_64/lib/gcc/aarch64-linux-android/4.9.x/../../../../aarch64-linux-android/bin/ld: cannot find -lmedialibrary
/home/specter/Development/Android/android-ndk-r13/toolchains/aarch64-linux-android-4.9/prebuilt/linux-x86_64/lib/gcc/aarch64-linux-android/4.9.x/../../../../aarch64-linux-android/bin/ld: skipping incompatible /home/specter/Development/vlc-android/medialibrary/sqlite-autoconf-3120200/build/.libs/libsqlite3.a when searching for -lsqlite3
/home/specter/Development/Android/android-ndk-r13/toolchains/aarch64-linux-android-4.9/prebuilt/linux-x86_64/lib/gcc/aarch64-linux-android/4.9.x/../../../../aarch64-linux-android/bin/ld: cannot find -lsqlite3
clang++: error: linker command failed with exit code 1 (use -v to see invocation)
make: *** [jni/obj/local/arm64-v8a/libmla.so] Error 1
make: Leaving directory `/home/specter/Development/vlc-android/medialibrary'
ndk-build failed
`

**Comment by mengzhidaren** [comment]
你最好加上我在环境中的设置export ANDROID_ABI=x86_64
你的错误log我不能判断出什么，只能猜测是其它的问题引起的，你可以试着去推断，x86_64要增加库兼容支持，你可以看看官方文档https://wiki.videolan.org/AndroidCompile/#Can.27t_run_aapt_or_adb_on_Linux_64-bit
