### ISSUE TITLE
播放RTSP流的时候，播放数秒后就没有声音了

### ISSUE THREAD

**Issue by jackycarry** [mengzhidaren/Vlc-sdk-lib#70]
播放RTSP流的时候，播放数秒后就没有声音了，如何解决

**Comment by mengzhidaren** [comment]
多测几个地址试下，如果用官方apk也有这个BUG  要么等官方更新，要么修改源码自已编译了

**Comment by jackycarry** [comment]
官方的没有这个问题~困扰

**Comment by mengzhidaren** [comment]
切换软硬解试下   我没改多少源码   只是做成通用的库了  强制软解的

**Comment by gymiicmc** [comment]
强制软解会不会导致播放大码率的视频会不流畅呢？

**Comment by mengzhidaren** [comment]
android手机配置本来就不均衡 ， 有的手机卡也正常  ，大码率在不同cpu上表现不一样是很正常的

**Comment by gymiicmc** [comment]
老哥老哥，我发现一个问题，就是播放视频如果结束了，切后台再切回来进行重播，貌似就只有声音但画面是黑屏的，不知道你那边有无这种现象。

**Comment by mengzhidaren** [comment]
你用的哪个版本的库 试下最新的3.0.2

**Comment by gymiicmc** [comment]
【播放结束，切后台，再回来，重新播放，黑屏】
用的libvlc2.5.17这个版本， 记得修复黑屏问题之前那个版本（2.5.14？）好像不会出现这个问题。这个问题也是昨天我才发现的，很隐秘。我刚试过，换了3.0.2这个库好像问题也没解决。
与这个问题同步出现的另外一个问题是，某些视频在播放时并没填满屏幕右边框（竖屏时播放）或者下边框（横屏时播放）。

一共就这两个问题。

**Comment by mengzhidaren** [comment]
等下个版本修改下  你先回退到2.5.15

**Comment by gymiicmc** [comment]
老哥老哥，最近都没你消息哦，期待你的更新
