### ISSUE TITLE
lib 怎么还是libvlc2.5.14

### ISSUE THREAD

**Issue by oy-paddy** [mengzhidaren/Vlc-sdk-lib#71]
hello,看你更新了引用为2.5.15，怎么你这个项目的lib还是显示libvlc2.5.14。是不是忘记改名啦？

**Comment by oy-paddy** [comment]
@mengzhidaren  hello,看你更新了引用为2.5.15，怎么你这个项目的lib还是显示libvlc2.5.14。是不是忘记改名啦？

**Comment by mengzhidaren** [comment]
只是修改了个BUG本来是2.5.141 太长了就2.5.15了  还是2.5.14的库  没变化

**Comment by oy-paddy** [comment]
@mengzhidaren 这是截图实现。你demo没体现出来


package org.videolan.vlc;


import android.content.Context;
import android.graphics.Bitmap;
import android.graphics.Matrix;
import android.graphics.SurfaceTexture;
import android.os.Environment;
import android.util.AttributeSet;
import android.util.Log;
import android.view.TextureView;


import org.videolan.libvlc.LibVLC;
import org.videolan.libvlc.Media;
import org.videolan.vlc.listener.MediaListenerEvent;
import org.videolan.vlc.listener.MediaPlayerControl;
import org.videolan.vlc.listener.VideoSizeChange;
import org.videolan.vlc.util.LogUtils;

import java.io.File;
import java.io.FileNotFoundException;
import java.io.FileOutputStream;
import java.io.IOException;
import java.io.OutputStream;
import java.text.SimpleDateFormat;
import java.util.Date;

/**
 * @author https://github.com/mengzhidaren
 */
public class VlcVideoView extends TextureView implements MediaPlayerControl, TextureView.SurfaceTextureListener, VideoSizeChange {
    private VlcPlayer videoMediaLogic;
    private final String tag = "VideoView";

    public VlcVideoView(Context context) {
        this(context, null);
    }

    public VlcVideoView(Context context, AttributeSet attrs) {
        this(context, attrs, 0);
    }

    public VlcVideoView(Context context, AttributeSet attrs, int defStyleAttr) {
        super(context, attrs, defStyleAttr);
        if (isInEditMode()) {
            return;
        }
        init(context);
    }

    public void setMediaListenerEvent(MediaListenerEvent mediaListenerEvent) {
        videoMediaLogic.setMediaListenerEvent(mediaListenerEvent);
    }

    @Override
    public boolean canControl() {
        return videoMediaLogic.canControl();
    }

    /**
     * 关闭avtivity时 停止时用
     */
    public void onStop() {
        videoMediaLogic.onStop();
    }

    /**
     * 退出应用时回收
     */
    public void onDestory() {
        if (videoMediaLogic != null)
            videoMediaLogic.onDestory();
        LogUtils.i(tag, "onDestory");
    }

    private void init(Context context) {
        videoMediaLogic = new VlcPlayer(context);
        videoMediaLogic.setVideoSizeChange(this);
        setSurfaceTextureListener(this);
    }

    public void setMediaPlayer(LibVLC libVLC) {
        videoMediaLogic.setMediaPlayer(libVLC);
    }

    public void setMedia(Media media) {
        videoMediaLogic.setMedia(media);
    }

    @Override
    public boolean isPrepare() {
        return videoMediaLogic.isPrepare();
    }


    @Override
    public void startPlay(String path) {
        videoMediaLogic.startPlay(path);
    }

    public void saveState() {
        videoMediaLogic.saveState();
    }

    @Override
    public void start() {
        videoMediaLogic.start();
    }

    /**
     * 重连 调用这个，不要调用onStop;
     */
    @Override
    public void pause() {
        videoMediaLogic.pause();
    }

    @Override
    public long getDuration() {
        return videoMediaLogic.getDuration();
    }

    @Override
    public long getCurrentPosition() {
        return videoMediaLogic.getCurrentPosition();
    }

    @Override
    public void seekTo(long pos) {
        videoMediaLogic.seekTo(pos);
    }

    @Override
    public boolean isPlaying() {
        return videoMediaLogic.isPlaying();
    }


    @Override
    public void setMirror(boolean mirror) {
        this.mirror = mirror;
        if (mirror) {
            setScaleX(-1f);
        } else {
            setScaleX(1f);
        }
    }

    private boolean mirror = false;

    @Override
    public boolean getMirror() {
        return mirror;
    }


    @Override
    public int getBufferPercentage() {
        return videoMediaLogic.getBufferPercentage();
    }

    @Override
    public boolean setPlaybackSpeedMedia(float speed) {
        return videoMediaLogic.setPlaybackSpeedMedia(speed);
    }

    @Override
    public float getPlaybackSpeed() {
        return videoMediaLogic.getPlaybackSpeed();
    }


    @Override
    public void setLoop(boolean isLoop) {
        videoMediaLogic.setLoop(isLoop);
    }

    @Override
    public boolean isLoop() {
        return videoMediaLogic.isLoop();
    }


    @Override
    public void onSurfaceTextureAvailable(SurfaceTexture surface, int width, int height) {
        LogUtils.i(tag, "onSurfaceTextureAvailable");
        videoMediaLogic.setSurface(surface);
    }

    @Override
    public void onSurfaceTextureSizeChanged(SurfaceTexture surface, int width, int height) {
        LogUtils.i(tag, "onSurfaceTextureSizeChanged");
        post(new Runnable() {
            @Override
            public void run() {
                adjustAspectRatio(mVideoWidth, mVideoHeight, rotation);
            }
        });
    }

    @Override
    public boolean onSurfaceTextureDestroyed(SurfaceTexture surface) {
        LogUtils.i(tag, "onSurfaceTextureDestroyed");
        videoMediaLogic.onSurfaceTextureDestroyed();
        return false;
    }

    @Override
    public void onSurfaceTextureUpdated(SurfaceTexture surface) {

    }

    //根据播放状态 打开关闭旋转动画
    @Override
    protected void onAttachedToWindow() {
        super.onAttachedToWindow();
        LogUtils.i(tag, "onAttachedToWindow");
        if (isInEditMode()) {
            return;
        }
        setKeepScreenOn(true);
    }

    @Override
    protected void onDetachedFromWindow() {
        super.onDetachedFromWindow();
        LogUtils.i(tag, "onDetachedFromWindow");
        if (isInEditMode()) {
            return;
        }
        setKeepScreenOn(false);
    }

    private void adjustAspectRatio(int videoWidth, int videoHeight, int rotation) {
        if (videoWidth * videoHeight == 0) {
            return;
        }
        int viewWidth = getWidth();
        int viewHeight = getHeight();
        double videoRatio = (double) viewWidth / (double) viewHeight;//显示比例
        double aspectRatio = (double) videoWidth / (double) videoHeight;//视频比例
        int newWidth, newHeight;
        if (videoWidth > videoHeight) {//正常比例16：9
            if (videoRatio > aspectRatio) {//16:9>16:10
                newWidth = (int) (viewHeight * aspectRatio);
                newHeight = viewHeight;
            } else {//16:9<16:8
                newWidth = viewWidth;
                newHeight = (int) (viewWidth / aspectRatio);
            }
        } else {//非正常可能是 90度
            //16:9>1:9
            newWidth = (int) (viewHeight * aspectRatio);
            newHeight = viewHeight;
        }
        float xoff = (viewWidth - newWidth) / 2f;
        float yoff = (viewHeight - newHeight) / 2f;
        Matrix txform = new Matrix();
        getTransform(txform);
        txform.setScale((float) newWidth / viewWidth, (float) newHeight
                / viewHeight);
        // txform.postRotate(10); // just for fun
        txform.postTranslate(xoff, yoff);
        setTransform(txform);
        if (rotation == 180) {
            setRotation(180);
        } else {
            setRotation(0);
        }
    }

    @Override
    protected void onLayout(boolean changed, int left, int top, int right, int bottom) {
        super.onLayout(changed, left, top, right, bottom);
        if (changed) {
            adjustAspectRatio(mVideoWidth, mVideoHeight, 0);
        }
    }

    private int mVideoWidth;
    private int mVideoHeight;

    public int getVideoRotation() {
        return rotation;
    }

    private int rotation = 0;

    @Override
    public void onVideoSizeChanged(int width, int height, int visibleWidth, int visibleHeight, int orientation) {
        LogUtils.i(tag, "onVideoSizeChanged   video=" + width + "x" + width + " visible="
                + visibleWidth + "x" + visibleHeight + "   orientation=" + orientation);
        if (width * height == 0) return;
        this.mVideoWidth = visibleWidth;
        this.mVideoHeight = visibleHeight;
        this.rotation = orientation;
        post(new Runnable() {
            @Override
            public void run() {
                adjustAspectRatio(mVideoWidth, mVideoHeight, rotation);
            }
        });
    }


    public boolean getBitmaps(String path)
    {
        String mPath = "";
        String name = "";
        if (path.equals("")) {
            mPath = Environment.getExternalStorageDirectory().toString()
                    + "/";
            SimpleDateFormat df = new SimpleDateFormat("yyyy-MM-dd HH-mm-ss");
            name = df.format(new Date());
            name =mPath+"/"+name+ ".jpg";
        }else
            name = path;



        // Toast.makeText(getApplicationContext(), "Capturing Screenshot: " + mPath, Toast.LENGTH_SHORT).show();

        Bitmap bm = this.getBitmap();
        if(bm == null)
            Log.e(tag,"bitmap is null");

        OutputStream fout = null;
        File imageFile = new File(name);

        try {
            fout = new FileOutputStream(imageFile);
            bm.compress(Bitmap.CompressFormat.PNG, 90, fout);
            fout.flush();
            fout.close();
            return true;
        } catch (FileNotFoundException e) {
            Log.e(tag, "FileNotFoundException");
            e.printStackTrace();
            return false;
        } catch (IOException e) {
            Log.e(tag, "IOException");
            e.printStackTrace();
            return false;
        }
    }
}

**Comment by oy-paddy** [comment]
谢谢你的思路，这是我的写法如下。    

public boolean getBitmaps(String path)
    {
        String mPath = "";
        String name = "";
        if (path.equals("")) {
            mPath = Environment.getExternalStorageDirectory().toString()
                    + "/";
            SimpleDateFormat df = new SimpleDateFormat("yyyy-MM-dd HH-mm-ss");
            name = df.format(new Date());
            name =mPath+"/"+name+ ".jpg";
        }else
            name = path;



        // Toast.makeText(getApplicationContext(), "Capturing Screenshot: " + mPath, Toast.LENGTH_SHORT).show();

        Bitmap bm = this.getBitmap();
        if(bm == null) {
            Log.e(tag, "bitmap is null");
            return false;
        }

        OutputStream fout = null;
        File imageFile = new File(name);

        try {
            fout = new FileOutputStream(imageFile);
            bm.compress(Bitmap.CompressFormat.PNG, 90, fout);
            fout.flush();
            fout.close();
            return true;
        } catch (FileNotFoundException e) {
            Log.e(tag, "FileNotFoundException");
            e.printStackTrace();
            return false;
        } catch (IOException e) {
            Log.e(tag, "IOException");
            e.printStackTrace();
            return false;
        }
    }
