### ISSUE TITLE
VLC无法播放爱奇艺m3u8视频地址

### ISSUE THREAD

**Issue by Greathfs** [mengzhidaren/Vlc-sdk-lib#73]
爱奇艺视频地址失效很快,所以我不打算提供播放地址
抓取地址方法如下:
![qq 20180119085833](https://user-images.githubusercontent.com/18097997/35137782-0d513c12-fd26-11e7-984c-d8e2bb3ea6f6.png)

**Comment by mengzhidaren** [comment]
可以用官方播放器测试  如果不支持 坐等更新吧

**Comment by Greathfs** [comment]
官方的也无法播放,这个问题关键怎么提供给官方呢? 官方的github没有issues这个选项

**Comment by mengzhidaren** [comment]
去官方仓库提问     https://code.videolan.org/videolan/vlc-android/issues
