### ISSUE TITLE
你好，作者

### ISSUE THREAD

**Issue by YubaKevin** [mengzhidaren/Vlc-sdk-lib#74]
我是一名刚从事安卓的工作者，
刚接触VLC，能否留下您的联系方式，
由于工作的需要，也是为了丰富自己的能力
愿意有偿向您学习。
我的邮箱535441862@qq.com

**Comment by mengzhidaren** [comment]
不用了，vlc太大了，我也一知半解

**Comment by YubaKevin** [comment]
能否实现录像功能

**Comment by mengzhidaren** [comment]
不知道   你自已看文档做吧   后期有时间我会追加的
