### ISSUE TITLE
多次打开关闭rtsp流无法播放

### ISSUE THREAD

**Issue by shuruncs** [mengzhidaren/Vlc-sdk-lib#75]
第一次播放正常，关闭播放页面重新打开rtsp就一直加载无法播放，显示socekt exception

**Comment by shuruncs** [comment]
刚才测试一段时间，发现不要调用videoplayer的ondestroy方法就可以了。只需要调用onstop

**Comment by mengzhidaren** [comment]
onDestroy在进程退出时调用
