### ISSUE TITLE
请问能获取到rtsp传过来的视频保存下来吗？

### ISSUE THREAD

**Issue by shuruncs** [mengzhidaren/Vlc-sdk-lib#80]
需要录制视频，有没有方法回调拆包后的音视频数据？

**Comment by mengzhidaren** [comment]
源代码有这功能  自已配置吧   --record-path <字符串型> 录制目录   --key-record <整型>   录制
                                 --image-out-ratio <整型> 录制比率

**Comment by shuruncs** [comment]
大佬，你这个说法我完全懵逼。我想问能不能再手机播放视频的时候，点一下按钮就开始录制视频存起来。需要一个java层的方法，你这个方法不懂。。

**Comment by mengzhidaren** [comment]
那你只等过完年来了  我在下个版本把录屏接口放出来  最近刚更2.9.0  还没提交

**Comment by shuruncs** [comment]
好的，坐等大佬实现，这个录屏应该也是一个比较强的需求。

**Comment by GirlFriendNotFind** [comment]
弱弱问下大佬现在支持截图和录像了吗？之前我使用旧版vlc去实现截图和录像，但是旧版在8.0上闪退，翻了网络好像除了vlc没什么好用的推荐了。。
