### ISSUE TITLE
开始播放本地文件时显示 绿色/灰色 乱码

### ISSUE THREAD

**Issue by KnIfER** [mengzhidaren/Vlc-sdk-lib#81]
此issue与另一个老外编译的库[类似](https://github.com/mrmaffen/vlc-android-sdk/issues/122)。
我测试的是3.0的那个vlc库。  
已检查视频源，没有问题。使用官方vlc播放器播放，一切正常。  
使用你或他编译的库，一开始播放的时候会有乱码现象。  mrmaffen编译的库，旧版未发现此现象。新版，一开始播放的时候会有乱码现象，且，使用seekbar将进度拖到最开始，会重现乱码现象。绿色乱码持续半秒至数秒不等。
[测试文件](http://pan.baidu.com/s/1raqlVWg)

**Comment by KnIfER** [comment]
刚刚测试了你编译的2.5版本的库，问题依旧，而且在我的kindle hdx android 5上显示灰色乱码，三星s7安卓7显示绿色乱码

**Comment by KnIfER** [comment]
[](https://pan.baidu.com/s/1qZ0ffWS)

[](https://pan.baidu.com/s/1cWf3uY)

**Comment by mengzhidaren** [comment]
等下个版本在修改   你先回退到2.5.15

**Comment by KnIfER** [comment]
根据老外提示已解决：
		ArrayList<String> options = new ArrayList(1);
		options.add("--vout=android-display");
		mLibVLC = new LibVLC(this,options);
