### ISSUE TITLE
你好，大牛

### ISSUE THREAD

**Issue by leleAichaoshen** [mengzhidaren/Vlc-sdk-lib#86]
首先谢谢你的sdk，其次我在播放在线MP4格式的视频的时候调用的player.startPlay(path)；方法，但是没有效果 ，不清楚为什么，求帮助

**Comment by leleAichaoshen** [comment]
libvlc stream: cannot seek (to offset 68460443) 有这个错误，我感觉是你直接防止黑屏跳转的问题

**Comment by leleAichaoshen** [comment]
我下载了你的demo，分别用了两个地址一个个内网一个外网：
        path = "http://flv2.bn.netease.com/tvmrepo/2016/4/M/Q/EBKQO95MQ/SD/EBKQO95MQ-mobile.mp4";
http://192.168.0.66:8080/videos/shaolin.mp4
这两个地址，第一个可以直接播放，但是第二个就是白屏

**Comment by mengzhidaren** [comment]
//3.0.2有点小问题 等下个版本修改下  先回退到2.5.15
   compile 'com.yyl.vlc:vlc-android-sdk:2.5.15'
