### ISSUE TITLE
Caching issue

### ISSUE THREAD

**Issue by c10ud** [mengzhidaren/Vlc-sdk-lib#87]
Hello,
I am using your compiled 'com.yyl.vlc:vlc-android-sdk:3.0.2' in my Android app and I am trying to obtain near-zero delay video from a RTSP source.

I am having difficulties getting sub-second delay and I saw this patch from VLC developers.

https://code.videolan.org/videolan/vlc-android/commit/142154e3abbad0d969dd8c5cd24652f275884a40

Can you try adding this to your builds? Thanks

**Comment by mengzhidaren** [comment]
I've tried this method to be very small，You can increase yourself

**Comment by c10ud** [comment]
I set these options in libvlc init and I fear they are being overwritten when media is started, that is why I ask:

        args.add("--rtsp-caching=0");
        args.add("--network-caching=0"); // probably overwritten in org\videolan\libvlc\Media.java
        args.add("--file-caching=0"); // probably overwritten in org\videolan\libvlc\Media.java
        args.add("--rtsp-timeout=5");
        args.add("--udp-timeout=5");
        args.add("--clock-synchro=0");
        args.add("--clock-jitter=0");
        args.add("--network-synchronisation");
        args.add("--no-drop-late-frames");
        args.add("--quiet-synchro");
        args.add("--sout-ts-dts-delay=100");
        args.add("--sout-ps-dts-delay=100");

        mLibVLC = new LibVLC(this, args);

**Comment by mengzhidaren** [comment]
No general environment
