### ISSUE TITLE
请问一下，如果buffing获取一直0，那要怎么处理？

### ISSUE THREAD

**Issue by huangcy3373** [mengzhidaren/Vlc-sdk-lib#9]

**Comment by mengzhidaren** [comment]
能描述清楚一点吗，是地址错了播不出来，还是播放器错了

**Comment by huangcy3373** [comment]
11-23 12:27:43.015 26252-26252/videolist.yyl.com.vlc_sdk_lib I/MainActivity: 支持 x86  armv7
11-23 12:27:43.175 26252-26252/videolist.yyl.com.vlc_sdk_lib D/MediaControl: eventPlayInit-----openClose=true
11-23 12:27:43.235 26252-32694/videolist.yyl.com.vlc_sdk_lib D/dalvikvm: threadid=18: thread exiting, not yet detached (count=0)
11-23 12:27:43.235 26252-32203/videolist.yyl.com.vlc_sdk_lib D/dalvikvm: threadid=14: thread exiting, not yet detached (count=0)
11-23 12:27:43.255 26252-32205/videolist.yyl.com.vlc_sdk_lib D/dalvikvm: threadid=17: thread exiting, not yet detached (count=0)
11-23 12:27:43.255 26252-32191/videolist.yyl.com.vlc_sdk_lib D/dalvikvm: threadid=13: thread exiting, not yet detached (count=0)
11-23 12:27:43.255 26252-26252/videolist.yyl.com.vlc_sdk_lib D/MediaControl: eventPlayInit-----openClose=true
11-23 12:27:43.265 26252-26252/videolist.yyl.com.vlc_sdk_lib D/MediaControl: eventBuffing-----buffing=0.0------show=true
11-23 12:27:43.285 26252-26252/videolist.yyl.com.vlc_sdk_lib I/Timeline: Timeline: Activity_idle id: android.os.BinderProxy@422aab20 time:18220309
11-23 12:27:43.355 26252-26252/videolist.yyl.com.vlc_sdk_lib D/MediaControl: eventPlay-----isPlaying=true
11-23 12:27:43.395 26252-26252/videolist.yyl.com.vlc_sdk_lib D/MediaControl: eventBuffing-----buffing=0.0------show=true
11-23 12:27:43.395 26252-26252/videolist.yyl.com.vlc_sdk_lib D/MediaControl: eventBuffing-----buffing=0.0------show=true
11-23 12:27:43.395 26252-26252/videolist.yyl.com.vlc_sdk_lib D/MediaControl: eventBuffing-----buffing=0.0------show=true
11-23 12:27:43.395 26252-26252/videolist.yyl.com.vlc_sdk_lib D/MediaControl: eventBuffing-----buffing=0.0------show=true
11-23 12:27:43.395 26252-26252/videolist.yyl.com.vlc_sdk_lib D/MediaControl: eventBuffing-----buffing=0.0------show=true
11-23 12:27:43.395 26252-26252/videolist.yyl.com.vlc_sdk_lib D/MediaControl: eventBuffing-----buffing=0.0------show=true
11-23 12:27:43.425 26252-26252/videolist.yyl.com.vlc_sdk_lib D/MediaControl: eventBuffing-----buffing=0.0------show=true
11-23 12:27:43.425 26252-26252/videolist.yyl.com.vlc_sdk_lib D/MediaControl: eventBuffing-----buffing=0.0------show=true
11-23 12:27:43.425 26252-26252/videolist.yyl.com.vlc_sdk_lib D/MediaControl: eventBuffing-----buffing=0.0------show=true
11-23 12:27:43.425 26252-26252/videolist.yyl.com.vlc_sdk_lib D/MediaControl: eventBuffing-----buffing=0.0------show=true
11-23 12:27:43.425 26252-26252/videolist.yyl.com.vlc_sdk_lib D/MediaControl: eventBuffing-----buffing=0.0------show=true
11-23 12:27:43.425 26252-26252/videolist.yyl.com.vlc_sdk_lib D/MediaControl: eventBuffing-----buffing=0.0------show=true
11-23 12:27:43.425 26252-26252/videolist.yyl.com.vlc_sdk_lib D/MediaControl: eventBuffing-----buffing=0.0------show=true
11-23 12:27:43.425 26252-26252/videolist.yyl.com.vlc_sdk_lib D/MediaControl: eventBuffing-----buffing=0.0------show=true
11-23 12:27:43.435 26252-26252/videolist.yyl.com.vlc_sdk_lib D/MediaControl: eventBuffing-----buffing=0.0------show=true
11-23 12:27:43.435 26252-26252/videolist.yyl.com.vlc_sdk_lib D/MediaControl: eventBuffing-----buffing=0.0------show=true
11-23 12:27:43.455 26252-26252/videolist.yyl.com.vlc_sdk_lib D/MediaControl: eventBuffing-----buffing=0.0------show=true
11-23 12:27:43.455 26252-26252/videolist.yyl.com.vlc_sdk_lib D/MediaControl: eventBuffing-----buffing=0.0------show=true
11-23 12:27:43.455 26252-26252/videolist.yyl.com.vlc_sdk_lib D/MediaControl: eventBuffing-----buffing=0.0------show=true
11-23 12:27:43.455 26252-26252/videolist.yyl.com.vlc_sdk_lib D/MediaControl: eventBuffing-----buffing=0.0------show=true
11-23 12:27:43.455 26252-26252/videolist.yyl.com.vlc_sdk_lib D/MediaControl: eventBuffing-----buffing=0.0------show=true
11-23 12:27:43.485 26252-26252/videolist.yyl.com.vlc_sdk_lib D/MediaControl: eventBuffing-----buffing=0.0------show=true
11-23 12:27:43.485 26252-26252/videolist.yyl.com.vlc_sdk_lib D/MediaControl: eventBuffing-----buffing=0.0------show=true
11-23 12:27:43.485 26252-26252/videolist.yyl.com.vlc_sdk_lib D/MediaControl: eventBuffing-----buffing=0.0------show=true
11-23 12:27:43.485 26252-26252/videolist.yyl.com.vlc_sdk_lib D/MediaControl: eventBuffing-----buffing=0.0------show=true
11-23 12:27:43.505 26252-26252/videolist.yyl.com.vlc_sdk_lib D/MediaControl: eventBuffing-----buffing=0.0------show=true
11-23 12:27:43.555 26252-26252/videolist.yyl.com.vlc_sdk_lib D/MediaControl: eventBuffing-----buffing=0.0------show=true
11-23 12:27:43.575 26252-26252/videolist.yyl.com.vlc_sdk_lib D/MediaControl: eventBuffing-----buffing=0.0------show=true
11-23 12:27:43.575 26252-26252/videolist.yyl.com.vlc_sdk_lib D/MediaControl: eventBuffing-----buffing=0.0------show=true
11-23 12:27:43.575 26252-26252/videolist.yyl.com.vlc_sdk_lib D/MediaControl: eventBuffing-----buffing=0.0------show=true
11-23 12:27:43.575 26252-26252/videolist.yyl.com.vlc_sdk_lib D/MediaControl: eventBuffing-----buffing=0.0------show=true
11-23 12:27:43.575 26252-26252/videolist.yyl.com.vlc_sdk_lib D/MediaControl: eventBuffing-----buffing=0.0------show=true
11-23 12:27:43.575 26252-26252/videolist.yyl.com.vlc_sdk_lib D/MediaControl: eventBuffing-----buffing=0.0------show=true
11-23 12:27:43.575 26252-26252/videolist.yyl.com.vlc_sdk_lib D/MediaControl: eventBuffing-----buffing=0.0------show=true
11-23 12:27:43.575 26252-26252/videolist.yyl.com.vlc_sdk_lib D/MediaControl: eventBuffing-----buffing=0.0------show=true
11-23 12:27:43.595 26252-26252/videolist.yyl.com.vlc_sdk_lib D/MediaControl: eventBuffing-----buffing=0.0------show=true
11-23 12:27:43.595 26252-26252/videolist.yyl.com.vlc_sdk_lib D/MediaControl: eventBuffing-----buffing=0.0------show=true
11-23 12:27:43.605 26252-26252/videolist.yyl.com.vlc_sdk_lib D/MediaControl: eventBuffing-----buffing=0.0------show=true
11-23 12:27:43.625 26252-26252/videolist.yyl.com.vlc_sdk_lib D/MediaControl: eventBuffing-----buffing=0.0------show=true
11-23 12:27:43.625 26252-26252/videolist.yyl.com.vlc_sdk_lib D/MediaControl: eventBuffing-----buffing=0.0------show=true
11-23 12:27:43.635 26252-26252/videolist.yyl.com.vlc_sdk_lib D/MediaControl: eventBuffing-----buffing=0.0------show=true
11-23 12:27:43.655 26252-26252/videolist.yyl.com.vlc_sdk_lib D/MediaControl: eventBuffing-----buffing=0.0------show=true
11-23 12:27:43.655 26252-26252/videolist.yyl.com.vlc_sdk_lib D/MediaControl: eventBuffing-----buffing=0.0------show=true
11-23 12:27:43.655 26252-26252/videolist.yyl.com.vlc_sdk_lib D/MediaControl: eventBuffing-----buffing=0.0------show=true
11-23 12:27:43.655 26252-26252/videolist.yyl.com.vlc_sdk_lib D/MediaControl: eventBuffing-----buffing=0.0------show=true
11-23 12:27:43.675 26252-26252/videolist.yyl.com.vlc_sdk_lib D/MediaControl: eventBuffing-----buffing=0.0------show=true
11-23 12:27:43.695 26252-26252/videolist.yyl.com.vlc_sdk_lib D/MediaControl: eventBuffing-----buffing=0.0------show=true
11-23 12:27:43.695 26252-26252/videolist.yyl.com.vlc_sdk_lib D/MediaControl: eventBuffing-----buffing=0.0------show=true
11-23 12:27:43.695 26252-26252/videolist.yyl.com.vlc_sdk_lib D/MediaControl: eventBuffing-----buffing=0.0------show=true
11-23 12:27:43.705 26252-26252/videolist.yyl.com.vlc_sdk_lib D/MediaControl: eventBuffing-----buffing=0.0------show=true
11-23 12:27:43.725 26252-26252/videolist.yyl.com.vlc_sdk_lib D/MediaControl: eventBuffing-----buffing=0.0------show=true
11-23 12:27:43.735 26252-26252/videolist.yyl.com.vlc_sdk_lib D/MediaControl: eventBuffing-----buffing=0.0------show=true
11-23 12:27:43.735 26252-26252/videolist.yyl.com.vlc_sdk_lib D/MediaControl: eventBuffing-----buffing=0.0------show=true
11-23 12:27:43.735 26252-26252/videolist.yyl.com.vlc_sdk_lib D/MediaControl: eventBuffing-----buffing=0.0------show=true
11-23 12:27:43.735 26252-26252/videolist.yyl.com.vlc_sdk_lib D/MediaControl: eventBuffing-----buffing=0.0------show=true
11-23 12:27:43.755 26252-26252/videolist.yyl.com.vlc_sdk_lib D/MediaControl: eventBuffing-----buffing=0.0------show=true
11-23 12:27:43.775 26252-26252/videolist.yyl.com.vlc_sdk_lib D/MediaControl: eventBuffing-----buffing=0.0------show=true
11-23 12:27:43.775 26252-26252/videolist.yyl.com.vlc_sdk_lib D/MediaControl: eventBuffing-----buffing=0.0------show=true
11-23 12:27:43.775 26252-26252/videolist.yyl.com.vlc_sdk_lib D/MediaControl: eventBuffing-----buffing=0.0------show=true
11-23 12:27:43.775 26252-26252/videolist.yyl.com.vlc_sdk_lib D/MediaControl: eventBuffing-----buffing=0.0------show=true
11-23 12:27:43.835 26252-26252/videolist.yyl.com.vlc_sdk_lib D/MediaControl: eventBuffing-----buffing=0.0------show=true
11-23 12:27:43.835 26252-26252/videolist.yyl.com.vlc_sdk_lib D/MediaControl: eventBuffing-----buffing=0.0------show=true
11-23 12:27:43.835 26252-26252/videolist.yyl.com.vlc_sdk_lib D/MediaControl: eventBuffing-----buffing=0.0------show=true
11-23 12:27:43.835 26252-26252/videolist.yyl.com.vlc_sdk_lib D/MediaControl: eventBuffing-----buffing=0.0------show=true
11-23 12:27:43.835 26252-26252/videolist.yyl.com.vlc_sdk_lib D/MediaControl: eventBuffing-----buffing=0.0------show=true
11-23 12:27:43.835 26252-26252/videolist.yyl.com.vlc_sdk_lib D/MediaControl: eventBuffing-----buffing=0.0------show=true
11-23 12:27:43.835 26252-26252/videolist.yyl.com.vlc_sdk_lib D/MediaControl: eventBuffing-----buffing=0.0------show=true
11-23 12:27:43.835 26252-26252/videolist.yyl.com.vlc_sdk_lib D/MediaControl: eventBuffing-----buffing=0.0------show=true
11-23 12:27:43.835 26252-26252/videolist.yyl.com.vlc_sdk_lib D/MediaControl: eventBuffing-----buffing=0.0------show=true
11-23 12:27:43.835 26252-26252/videolist.yyl.com.vlc_sdk_lib D/MediaControl: eventBuffing-----buffing=0.0------show=true
11-23 12:27:43.855 26252-26252/videolist.yyl.com.vlc_sdk_lib D/MediaControl: eventBuffing-----buffing=0.0------show=true
11-23 12:27:43.895 26252-26252/videolist.yyl.com.vlc_sdk_lib D/MediaControl: eventBuffing-----buffing=0.0------show=true
11-23 12:27:43.895 26252-26252/videolist.yyl.com.vlc_sdk_lib D/MediaControl: eventBuffing-----buffing=0.0------show=true
11-23 12:27:43.895 26252-26252/videolist.yyl.com.vlc_sdk_lib D/MediaControl: eventBuffing-----buffing=0.0------show=true
11-23 12:27:43.895 26252-26252/videolist.yyl.com.vlc_sdk_lib D/MediaControl: eventBuffing-----buffing=0.0------show=true
11-23 12:27:43.895 26252-26252/videolist.yyl.com.vlc_sdk_lib D/MediaControl: eventBuffing-----buffing=0.0------show=true
11-23 12:27:43.915 26252-26252/videolist.yyl.com.vlc_sdk_lib D/MediaControl: eventBuffing-----buffing=0.0------show=true
11-23 12:27:43.915 26252-26252/videolist.yyl.com.vlc_sdk_lib D/MediaControl: eventBuffing-----buffing=0.0------show=true
11-23 12:27:43.945 26252-26252/videolist.yyl.com.vlc_sdk_lib D/MediaControl: eventBuffing-----buffing=0.0------show=true
11-23 12:27:43.945 26252-26252/videolist.yyl.com.vlc_sdk_lib D/MediaControl: eventBuffing-----buffing=0.0------show=true
11-23 12:27:43.955 26252-26252/videolist.yyl.com.vlc_sdk_lib D/MediaControl: eventBuffing-----buffing=0.0------show=true
11-23 12:27:43.985 26252-26252/videolist.yyl.com.vlc_sdk_lib D/MediaControl: eventBuffing-----buffing=0.0------show=true
11-23 12:27:43.985 26252-26252/videolist.yyl.com.vlc_sdk_lib D/MediaControl: eventBuffing-----buffing=0.0------show=true
11-23 12:27:44.005 26252-26252/videolist.yyl.com.vlc_sdk_lib D/MediaControl: eventBuffing-----buffing=0.0------show=true
11-23 12:27:44.005 26252-26252/videolist.yyl.com.vlc_sdk_lib D/MediaControl: eventBuffing-----buffing=0.0------show=true
11-23 12:27:44.005 26252-26252/videolist.yyl.com.vlc_sdk_lib D/MediaControl: eventBuffing-----buffing=0.0------show=true
11-23 12:27:44.025 26252-26252/videolist.yyl.com.vlc_sdk_lib D/MediaControl: eventBuffing-----buffing=0.0------show=true
11-23 12:27:44.025 26252-26252/videolist.yyl.com.vlc_sdk_lib D/MediaControl: eventBuffing-----buffing=0.0------show=true
11-23 12:27:44.035 26252-26252/videolist.yyl.com.vlc_sdk_lib D/MediaControl: eventBuffing-----buffing=0.0------show=true
11-23 12:27:44.035 26252-26252/videolist.yyl.com.vlc_sdk_lib D/MediaControl: eventBuffing-----buffing=0.0------show=true
11-23 12:27:44.045 26252-26252/videolist.yyl.com.vlc_sdk_lib D/MediaControl: eventBuffing-----buffing=0.0------show=true
11-23 12:27:44.055 26252-26252/videolist.yyl.com.vlc_sdk_lib D/MediaControl: eventBuffing-----buffing=0.0------show=true
11-23 12:27:44.055 26252-26252/videolist.yyl.com.vlc_sdk_lib D/MediaControl: eventBuffing-----buffing=0.0------show=true
11-23 12:27:44.055 26252-26252/videolist.yyl.com.vlc_sdk_lib D/MediaControl: eventBuffing-----buffing=0.0------show=true
11-23 12:27:44.055 26252-26252/videolist.yyl.com.vlc_sdk_lib D/MediaControl: eventBuffing-----buffing=0.0------show=true
11-23 12:27:44.075 26252-26252/videolist.yyl.com.vlc_sdk_lib D/MediaControl: eventBuffing-----buffing=0.0------show=true
11-23 12:27:44.095 26252-26252/videolist.yyl.com.vlc_sdk_lib D/MediaControl: eventBuffing-----buffing=0.0------show=true
11-23 12:27:44.095 26252-26252/videolist.yyl.com.vlc_sdk_lib D/MediaControl: eventBuffing-----buffing=0.0------show=true
11-23 12:27:44.105 26252-26252/videolist.yyl.com.vlc_sdk_lib D/MediaControl: eventBuffing-----buffing=0.0------show=true
11-23 12:27:44.105 26252-26252/videolist.yyl.com.vlc_sdk_lib D/MediaControl: eventBuffing-----buffing=0.0------show=true
11-23 12:27:44.105 26252-26252/videolist.yyl.com.vlc_sdk_lib D/MediaControl: eventBuffing-----buffing=0.0------show=true
11-23 12:27:44.135 26252-26252/videolist.yyl.com.vlc_sdk_lib D/MediaControl: eventBuffing-----buffing=0.0------show=true
11-23 12:27:44.135 26252-26252/videolist.yyl.com.vlc_sdk_lib D/MediaControl: eventBuffing-----buffing=0.0------show=true
11-23 12:27:44.135 26252-26252/videolist.yyl.com.vlc_sdk_lib D/MediaControl: eventBuffing-----buffing=0.0------show=true
11-23 12:27:44.135 26252-26252/videolist.yyl.com.vlc_sdk_lib D/MediaControl: eventBuffing-----buffing=0.0------show=true
11-23 12:27:44.205 26252-26252/videolist.yyl.com.vlc_sdk_lib D/MediaControl: eventBuffing-----buffing=0.0------show=true
11-23 12:27:44.205 26252-26252/videolist.yyl.com.vlc_sdk_lib D/MediaControl: eventBuffing-----buffing=0.0------show=true
11-23 12:27:44.205 26252-26252/videolist.yyl.com.vlc_sdk_lib D/MediaControl: eventBuffing-----buffing=0.0------show=true
11-23 12:27:44.205 26252-26252/videolist.yyl.com.vlc_sdk_lib D/MediaControl: eventBuffing-----buffing=0.0------show=true
11-23 12:27:44.205 26252-26252/videolist.yyl.com.vlc_sdk_lib D/MediaControl: eventBuffing-----buffing=0.0------show=true
11-23 12:27:44.205 26252-26252/videolist.yyl.com.vlc_sdk_lib D/MediaControl: eventBuffing-----buffing=0.0------show=true
11-23 12:27:44.205 26252-26252/videolist.yyl.com.vlc_sdk_lib D/MediaControl: eventBuffing-----buffing=0.0------show=true
11-23 12:27:44.205 26252-26252/videolist.yyl.com.vlc_sdk_lib D/MediaControl: eventBuffing-----buffing=0.0------show=true
11-23 12:27:44.205 26252-26252/videolist.yyl.com.vlc_sdk_lib D/MediaControl: eventBuffing-----buffing=0.0------show=true
11-23 12:27:44.225 26252-26252/videolist.yyl.com.vlc_sdk_lib D/MediaControl: eventBuffing-----buffing=0.0------show=true
11-23 12:27:44.245 26252-26252/videolist.yyl.com.vlc_sdk_lib D/MediaControl: eventBuffing-----buffing=0.0------show=true
11-23 12:27:44.265 26252-26252/videolist.yyl.com.vlc_sdk_lib D/MediaControl: eventBuffing-----buffing=0.0------show=true
11-23 12:27:44.265 26252-26252/videolist.yyl.com.vlc_sdk_lib D/MediaControl: eventBuffing-----buffing=0.0------show=true
11-23 12:27:44.285 26252-26252/videolist.yyl.com.vlc_sdk_lib D/MediaControl: eventBuffing-----buffing=0.0------show=true
11-23 12:27:44.285 26252-26252/videolist.yyl.com.vlc_sdk_lib D/MediaControl: eventBuffing-----buffing=0.0------show=true
11-23 12:27:44.285 26252-26252/videolist.yyl.com.vlc_sdk_lib D/MediaControl: eventBuffing-----buffing=0.0------show=true
11-23 12:27:44.285 26252-26252/videolist.yyl.com.vlc_sdk_lib D/MediaControl: eventBuffing-----buffing=0.0------show=true
11-23 12:27:44.285 26252-26252/videolist.yyl.com.vlc_sdk_lib D/MediaControl: eventBuffing-----buffing=0.0------show=true
11-23 12:27:44.285 26252-26252/videolist.yyl.com.vlc_sdk_lib D/MediaControl: eventBuffing-----buffing=0.0------show=true
11-23 12:27:44.285 26252-26252/videolist.yyl.com.vlc_sdk_lib D/MediaControl: eventBuffing-----buffing=0.0------show=true
11-23 12:27:44.315 26252-26252/videolist.yyl.com.vlc_sdk_lib D/MediaControl: eventBuffing-----buffing=0.0------show=true
11-23 12:27:44.325 26252-26252/videolist.yyl.com.vlc_sdk_lib D/MediaControl: eventBuffing-----buffing=0.0------show=true
11-23 12:27:44.325 26252-26252/videolist.yyl.com.vlc_sdk_lib D/MediaControl: eventBuffing-----buffing=0.0------show=true
11-23 12:27:44.325 26252-26252/videolist.yyl.com.vlc_sdk_lib D/MediaControl: eventBuffing-----buffing=0.0------show=true
11-23 12:27:44.325 26252-26252/videolist.yyl.com.vlc_sdk_lib D/MediaControl: eventBuffing-----buffing=0.0------show=true
11-23 12:27:44.335 26252-26252/videolist.yyl.com.vlc_sdk_lib D/MediaControl: eventBuffing-----buffing=0.0------show=true
11-23 12:27:44.365 26252-26252/videolist.yyl.com.vlc_sdk_lib D/MediaControl: eventBuffing-----buffing=0.0------show=true
11-23 12:27:44.365 26252-26252/videolist.yyl.com.vlc_sdk_lib D/MediaControl: eventBuffing-----buffing=0.0------show=true
11-23 12:27:44.365 26252-26252/videolist.yyl.com.vlc_sdk_lib D/MediaControl: eventBuffing-----buffing=0.0------show=true
11-23 12:27:44.365 26252-26252/videolist.yyl.com.vlc_sdk_lib D/MediaControl: eventBuffing-----buffing=0.0------show=true
11-23 12:27:44.385 26252-26252/videolist.yyl.com.vlc_sdk_lib D/MediaControl: eventBuffing-----buffing=0.0------show=true
11-23 12:27:44.425 26252-26252/videolist.yyl.com.vlc_sdk_lib D/MediaControl: eventBuffing-----buffing=0.0------show=true
11-23 12:27:44.425 26252-26252/videolist.yyl.com.vlc_sdk_lib D/MediaControl: eventBuffing-----buffing=0.0------show=true
11-23 12:27:44.425 26252-26252/videolist.yyl.com.vlc_sdk_lib D/MediaControl: eventBuffing-----buffing=0.0------show=true
11-23 12:27:44.425 26252-26252/videolist.yyl.com.vlc_sdk_lib D/MediaControl: eventBuffing-----buffing=0.0------show=true
11-23 12:27:44.445 26252-26252/videolist.yyl.com.vlc_sdk_lib D/MediaControl: eventBuffing-----buffing=0.0------show=true
11-23 12:27:44.445 26252-26252/videolist.yyl.com.vlc_sdk_lib D/MediaControl: eventBuffing-----buffing=0.0------show=true
11-23 12:27:44.445 26252-26252/videolist.yyl.com.vlc_sdk_lib D/MediaControl: eventBuffing-----buffing=0.0------show=true
11-23 12:27:44.445 26252-26252/videolist.yyl.com.vlc_sdk_lib D/MediaControl: eventBuffing-----buffing=0.0------show=true
11-23 12:27:44.445 26252-26252/videolist.yyl.com.vlc_sdk_lib D/MediaControl: eventBuffing-----buffing=0.0------show=true
11-23 12:27:44.465 26252-26252/videolist.yyl.com.vlc_sdk_lib D/MediaControl: eventBuffing-----buffing=0.0------show=true
11-23 12:27:44.495 26252-26252/videolist.yyl.com.vlc_sdk_lib D/MediaControl: eventBuffing-----buffing=0.0------show=true
11-23 12:27:44.505 26252-26252/videolist.yyl.com.vlc_sdk_lib D/MediaControl: eventBuffing-----buffing=0.0------show=true
11-23 12:27:44.505 26252-26252/videolist.yyl.com.vlc_sdk_lib D/MediaControl: eventBuffing-----buffing=0.0------show=true
11-23 12:27:44.505 26252-26252/videolist.yyl.com.vlc_sdk_lib D/MediaControl: eventBuffing-----buffing=0.0------show=true
11-23 12:27:44.525 26252-26252/videolist.yyl.com.vlc_sdk_lib D/MediaControl: eventBuffing-----buffing=0.0------show=true
11-23 12:27:44.535 26252-26252/videolist.yyl.com.vlc_sdk_lib D/MediaControl: eventBuffing-----buffing=0.0------show=true
后面是一直取不到

**Comment by huangcy3373** [comment]
流应该没问题，这个情况五次里面出现三次，有两次又能正常打开的

**Comment by mengzhidaren** [comment]
我没遇到过这问题，在这之前有点像我公司路由器做dns视频拦截时的情况 ，确认下你的路由器和测试机没问题 在判断原因吧
