### ISSUE TITLE
关于vlc播放延迟的问题

### ISSUE THREAD

**Issue by andriodZ** [mengzhidaren/Vlc-sdk-lib#93]
你好,大神,我自己编译了vlc-android,实现播放rtsp,但是延迟2秒左右,修改了libvlc-module.c下的延迟设置,java层设置的时300ms,但是依然没有效果,是否需要修改其它地方,感谢

**Comment by andriodZ** [comment]
另外再请教一个问题,我在vlc里面添加了录像功能,但是输出格式是AVI的,怎么才能修改录像的输出格式

**Comment by OneDayNoMore** [comment]
不知道为题是否解决了么，我也遇上相同的问题

**Comment by ILoveLin** [comment]
不知道为题是否解决了么，我也遇上相同的问题
