### ISSUE TITLE
画面卡住，声音再走，隔几秒才播放下一帧。大牛帮忙看看什么原因？

### ISSUE THREAD

**Issue by Oliven09** [mengzhidaren/Vlc-sdk-lib#95]
04-04 09:38:07.609 30110-31243/com.szdq.elinksmart E/VLC: [69045328/7a0b] avcodec decoder: more than 5 seconds of late video -> dropping frame (computer too slow ?)
04-04 09:38:07.609 30110-31243/com.szdq.elinksmart E/VLC: [69045328/7a0b] avcodec decoder: more than 5 seconds of late video -> dropping frame (computer too slow ?)
04-04 09:38:07.609 30110-31243/com.szdq.elinksmart E/VLC: [69045328/7a0b] avcodec decoder: more than 5 seconds of late video -> dropping frame (computer too slow ?)
04-04 09:38:07.609 30110-31243/com.szdq.elinksmart E/VLC: [69045328/7a0b] avcodec decoder: more than 5 seconds of late video -> dropping frame (computer too slow ?)
04-04 09:38:07.609 30110-31243/com.szdq.elinksmart E/VLC: [69045328/7a0b] avcodec decoder: more than 5 seconds of late video -> dropping frame (computer too slow ?)
04-04 09:38:07.609 30110-31243/com.szdq.elinksmart E/VLC: [69045328/7a0b] avcodec decoder: more than 5 seconds of late video -> dropping frame (computer too slow ?)
04-04 09:38:07.609 30110-31243/com.szdq.elinksmart E/VLC: [69045328/7a0b] avcodec decoder: more than 5 seconds of late video -> dropping frame (computer too slow ?)
04-04 09:38:07.609 30110-31243/com.szdq.elinksmart E/VLC: [69045328/7a0b] avcodec decoder: more than 5 seconds of late video -> dropping frame (computer too slow ?)
04-04 09:38:07.709 30110-30321/com.szdq.elinksmart E/VLC-std: [h264 @ 0x6f72a9f0] reference picture missing during reorder
04-04 09:38:07.709 30110-30321/com.szdq.elinksmart E/VLC-std: [h264 @ 0x6f72a9f0] reference picture missing during reorder
                                                              [h264 @ 0x6f72a9f0] Missing reference picture, default is 2147483647
04-04 09:38:07.709 30110-30321/com.szdq.elinksmart E/VLC-std: [h264 @ 0x6f72a9f0] Missing reference picture, default is 2147483647
04-04 09:38:07.709 30110-30321/com.szdq.elinksmart E/VLC-std: [h264 @ 0x69391d20] reference picture missing during reorder
                                                              [h264 @ 0x69391d20] reference picture missing during reorder
                                                              [h264 @ 0x69391d20] Missing reference picture, default is 65856
                                                              [h264 @ 0x69391d20] Missing reference picture, default is 65856
04-04 09:38:07.719 30110-30321/com.szdq.elinksmart E/VLC-std: [h264 @ 0x78d1f980] reference picture missing during reorder
                                                              [h264 @ 0x78d1f980] Missing reference picture, default is 2147483647
04-04 09:38:07.719 30110-30321/com.szdq.elinksmart E/VLC-std: [h264 @ 0x69264c40] mmco: unref short failure
                                                              [h264 @ 0x69264c40] mmco: unref short failure
                                                              [h264 @ 0x69264c40] number of reference frames (0+5) exceeds max (4; probably corrupt input), discarding one
04-04 09:38:07.719 30110-30321/com.szdq.elinksmart E/VLC-std: [h264 @ 0x69264c40] 
04-04 09:38:07.719 30110-30321/com.szdq.elinksmart E/VLC-std: reference picture missing during reorder
04-04 09:38:07.719 30110-30321/com.szdq.elinksmart E/VLC-std: [h264 @ 0x69264c40] 
04-04 09:38:07.719 30110-30321/com.szdq.elinksmart E/VLC-std: Missing reference picture, default is 65857

**Comment by mengzhidaren** [comment]
换我刚上传的3.0.5
