### ISSUE TITLE
试试配合surfaceview添加两指缩放功能……

### ISSUE THREAD

**Issue by KnIfER** [mengzhidaren/Vlc-sdk-lib#97]
安卓7.0等版本只需要在mSurfaceView的容器视图的ontouch里：  
```
mSurfaceView.setScaleX(scaleT);
mSurfaceView.setScaleY(scaleT);
```
但是，在kindle hdx 安卓5.6,setScaleX只会缩放mSurfaceView的view部分，而不会缩放其内容。    
另一个缩放的途径是:  
```
ViewGroup.LayoutParams lp = mSurfaceView.getLayoutParams();
lp.height = (int) (mVideoHeight*scaleT);
lp.width = (int)  (mVideoWidth*scaleT);
mSurfaceView.setLayoutParams(lp);
```
但是卡顿不说，设置LayoutParams 一般不能超过父容器大小，所以放大会有问题。  
再一个就是使用动画缩放，我没试……

**Comment by mengzhidaren** [comment]
关于UI层的控制，后期有时间可以单独出个view适配一下，目前还不在计划里

**Comment by KnIfER** [comment]
刚刚发现 关于LayoutParams 的方案，要把surfaceview放在一个framelayout里卖弄，不然就会放大会有问题。
