### ISSUE TITLE
不知道可不可以多通道播放的呢？

### ISSUE THREAD

**Issue by GirlFriendNotFind** [mengzhidaren/Vlc-sdk-lib#99]

**Comment by mengzhidaren** [comment]
可以  但是要自已适配

**Comment by GirlFriendNotFind** [comment]
ヽ(￣▽￣)ﾉ大佬有没有伪代码可以参考下或者提示一下呢，我想放在recycleview里播放但是疑惑播放器释放的问题，目前想做最多9路播放，可以切换1路4路9路这样

**Comment by GirlFriendNotFind** [comment]
创建的话频繁创建销毁播放器不太好吧，播放1通道的时候只有一个播放器，4通道创建多三个，切回1再切9通道不是要销毁3个再创建7个，或者一开始就创建9个保存起来？布局的变化也比较苦恼，除了recycleview暂时没想到怎样切换这些1,4,9的分屏

**Comment by mengzhidaren** [comment]
创建对像是不消耗资源的，只有解码时和绘制到surface时会消耗cpu的资源，可以用多线程队列解决，注意不要同时解码太多视频，没有太多很难的点，剩下的UI适配看你的基本功了
